# Generated by Django 5.2 on 2026-04-09 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiscal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='certificados/%Y/%m/')),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('nf_saida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificado', to='fiscal.nfesaida')),
            ],
            options={
                'ordering': ['-gerado_em'],
            },
        ),
    ]
