# Generated by Django 5.2 on 2026-07-08 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0012_sequencia_certificado_qualidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCertificadoFornecedorCorrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('corrida', models.CharField(blank=True, max_length=64)),
                ('lote', models.CharField(blank=True, max_length=64)),
                ('quantidade', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('item_certificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corridas_adicionais', to='qualidade.itemcertificadofornecedorentrada')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
