# Generated by Django 5.2 on 2026-09-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0013_itemcertificadofornecedorcorrida'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcertificadofornecedorcorrida',
            name='composicao_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='itemcertificadofornecedorcorrida',
            name='ensaio_impacto_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='itemcertificadofornecedorcorrida',
            name='ensaio_tracao_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
