# Generated by Django 6.1.1 on 2026-10-07 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0015_backfill_corrida_dados_tecnicos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCertificadoQualidadeCorrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('corrida', models.CharField(blank=True, max_length=64)),
                ('lote', models.CharField(blank=True, max_length=64)),
                ('quantidade', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('composicao_json', models.JSONField(blank=True, default=dict)),
                ('ensaio_tracao_json', models.JSONField(blank=True, default=dict)),
                ('ensaio_impacto_json', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('item_certificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corridas_adicionais', to='qualidade.itemcertificadoqualidade')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
