# Generated by Django 6.1.1 on 2026-10-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0016_itemcertificadoqualidadecorrida'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadoqualidade',
            name='rastreabilidade_status_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot do status de rastreabilidade no momento da emissão. Usado para congelar a avaliação em CQs emitidos.'),
        ),
    ]
