# Generated by Django 6.1.1 on 2026-10-07 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0017_certificadoqualidade_rastreabilidade_status_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadoqualidade',
            name='substituido_por',
            field=models.ForeignKey(blank=True, help_text='Versão mais recente que substituiu este CQ (reemissão).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitui', to='qualidade.certificadoqualidade'),
        ),
        migrations.AlterField(
            model_name='certificadoqualidade',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('emitido', 'Emitido'), ('cancelado', 'Cancelado'), ('substituido', 'Substituído')], default='rascunho', max_length=16),
        ),
    ]
