# Generated by Django 5.2 on 2026-04-09 17:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ncm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'verbose_name': 'NCM',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Polegada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True)),
                ('descricao', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Polegada',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figura', models.CharField(max_length=32)),
                ('sufixo', models.CharField(max_length=32)),
                ('schedule', models.CharField(max_length=32)),
                ('polegada_principal', models.CharField(max_length=32)),
                ('polegada_secundaria', models.CharField(blank=True, max_length=32)),
                ('descricao', models.CharField(max_length=512)),
                ('material', models.CharField(blank=True, max_length=128)),
                ('tipo_peca', models.CharField(blank=True, max_length=128)),
                ('pressao_nominal', models.CharField(blank=True, max_length=64)),
                ('norma', models.CharField(blank=True, max_length=128)),
                ('conexao', models.CharField(blank=True, max_length=128)),
                ('ncm', models.CharField(blank=True, max_length=16)),
                ('preco_custo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('preco_venda', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('codigo_completo', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'ordering': ['codigo_completo'],
            },
        ),
    ]
