# Generated by Django 5.2 on 2026-04-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_produto_unidades_compra_obs_conversao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiaproduto',
            name='separador_base_medidas',
            field=models.CharField(default='.', help_text='Separador entre prefixo (figura[+rosca][+schedule]) e parte de polegadas; use _ para padrão tipo 6038_005.', max_length=1),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo_completo',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='roscaconexao',
            name='codigo',
            field=models.CharField(help_text='Código no produto (ex.: N, S). Vazio = BSP / padrão da família.', max_length=16, unique=True),
        ),
    ]
