# Generated by Django 5.2 on 2026-04-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_ncm_campos_importacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polegada',
            options={'ordering': ['valor_decimal', 'codigo_oficial'], 'verbose_name': 'Polegada'},
        ),
        migrations.AddField(
            model_name='polegada',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='polegada',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='polegada',
            name='codigo_oficial',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='polegada',
            name='observacoes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='polegada',
            name='origem',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='polegada',
            name='valor_decimal',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='polegada',
            name='valor_mm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
