# Generated by Django 5.2 on 2026-05-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_popular_codigo_oficial_polegada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleespessura',
            options={'ordering': ['ordem', 'codigo_schedule'], 'verbose_name': 'Schedule / Espessura'},
        ),
        migrations.AddField(
            model_name='scheduleespessura',
            name='aplicacao',
            field=models.CharField(choices=[('CARBONO', 'Carbono'), ('INOX', 'Inox'), ('AMBOS', 'Ambos'), ('OUTRO', 'Outro')], default='AMBOS', max_length=16),
        ),
        migrations.AddField(
            model_name='scheduleespessura',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='scheduleespessura',
            name='observacoes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='scheduleespessura',
            name='ordem',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
