# Generated by Django 5.2 on 2026-05-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0014_familia_tipo_dimensional_produto_od_mm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polegada',
            options={'ordering': ['tipo_medida', 'valor_decimal', 'codigo_oficial'], 'verbose_name': 'Polegada'},
        ),
        migrations.AddField(
            model_name='polegada',
            name='tipo_medida',
            field=models.CharField(choices=[('NPS', 'NPS / nominal'), ('OD', 'OD / diâmetro externo real')], db_index=True, default='OD', max_length=8),
        ),
        migrations.AlterField(
            model_name='polegada',
            name='codigo',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='polegada',
            name='codigo_oficial',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddConstraint(
            model_name='polegada',
            constraint=models.UniqueConstraint(fields=('tipo_medida', 'codigo_oficial'), name='uq_polegada_tipo_codigo_oficial'),
        ),
        migrations.AddConstraint(
            model_name='polegada',
            constraint=models.UniqueConstraint(fields=('tipo_medida', 'descricao'), name='uq_polegada_tipo_descricao'),
        ),
    ]
