# Generated by Django 5.2 on 2026-05-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0015_alter_polegada_options_polegada_tipo_medida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='dimensoes_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='familiaproduto',
            name='tipo_dimensional',
            field=models.CharField(choices=[('SIMPLES', 'Simples (somente regra de código)'), ('NPS', 'NPS — polegada nominal'), ('NPS_SCHEDULE', 'NPS + Schedule (SCH)'), ('REDUCAO_NPS', 'Redução NPS + Schedule'), ('ROSCA', 'Rosca / conexão (orientação)'), ('ROSCA_X_ROSCA', 'Rosca x Rosca (orientação)'), ('NPS_X_ROSCA', 'NPS x Rosca'), ('OD_POLEGADA', 'OD em polegada (não é NPS/SCH)'), ('OD_POLEGADA_X_ROSCA', 'OD em polegada x Rosca'), ('OD_MM', 'OD em mm (tubo / dimensional)'), ('OD_MM_X_ESPESSURA', 'OD mm + espessura mm'), ('OD_MM_X_ESPESSURA_X_COMPRIMENTO', 'OD mm + espessura + comprimento'), ('CHAPA_MM', 'Chapa em mm (espessura x largura x comprimento)'), ('CHAPA_FURO_MM', 'Chapa com furo em mm (furo x espessura x largura x comprimento)'), ('BARRA_CHATA_MM', 'Barra chata em mm (largura x espessura [x comprimento])'), ('METALON_MM', 'Metalon em mm (altura x largura x espessura)'), ('CANTONEIRA_MM', 'Cantoneira em mm (aba x espessura [x comprimento])'), ('CANTONEIRA_POLEGADA', 'Cantoneira em polegada (aba x espessura)'), ('DIMENSIONAL_LIVRE_CONTROLADO', 'Dimensional livre controlado'), ('FLANGE', 'Flange (orientação)'), ('VALVULA', 'Válvula (orientação)'), ('MANUAL', 'Dimensional manual / sem padrão automático'), ('LEGADO', 'Legado / misto (orientação)')], default='SIMPLES', help_text='Significado dimensional dos campos (rótulos, obrigatoriedade, descrição). A montagem do código continua definida apenas por tipo_regra_codigo.', max_length=48),
        ),
    ]
