# Generated by Django 5.2 on 2026-05-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0016_produto_dimensoes_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiaproduto',
            name='categoria_produto',
            field=models.CharField(choices=[('PRODUTO_TECNICO', 'Produto técnico'), ('MATERIAL_DIMENSIONAL', 'Material dimensional'), ('MANUAL_FABRICANTE', 'Produto manual/fabricante')], default='PRODUTO_TECNICO', max_length=32),
        ),
    ]
