# Generated by Django 5.2 on 2026-05-30 02:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_cliente_informacoes_complementares_nfe'),
        ('produtos', '0021_alter_familia_tipo_dimensional_regra_pvc_pu'),
    ]

    operations = [
        migrations.CreateModel(
            name='FornecedorComposicaoEquivalencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_raiz_fornecedor', models.CharField(blank=True, db_index=True, max_length=8)),
                ('cnpj_filial_fornecedor', models.CharField(blank=True, db_index=True, max_length=14)),
                ('escopo_cnpj', models.CharField(choices=[('filial', 'Somente filial'), ('raiz', 'CNPJ raiz'), ('fornecedor', 'Fornecedor cadastrado')], default='raiz', max_length=16)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('tolerancia_valor_percentual', models.DecimalField(decimal_places=4, default=Decimal('0.5'), max_digits=7)),
                ('tolerancia_valor_absoluto', models.DecimalField(decimal_places=2, default=Decimal('0.05'), max_digits=14)),
                ('tolerancia_quantidade', models.DecimalField(decimal_places=4, default=Decimal('0.01'), max_digits=14)),
                ('ativo', models.BooleanField(default=True)),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('sugestao_confirmada', 'Sugestão confirmada'), ('importacao_historica', 'Importação histórica')], default='manual', max_length=32)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equivalencias_composicao', to='cadastros.fornecedor')),
                ('produto_interno_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equivalencias_composicao_fornecedor', to='produtos.produto')),
            ],
            options={
                'ordering': ['fornecedor_id', 'produto_interno_final_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FornecedorComposicaoEquivalenciaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_fornecedor', models.CharField(blank=True, max_length=64)),
                ('descricao_fornecedor_normalizada', models.CharField(blank=True, max_length=512)),
                ('ncm_fornecedor', models.CharField(blank=True, max_length=8)),
                ('quantidade_componente_por_produto_final', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=14)),
                ('unidade', models.CharField(blank=True, max_length=16)),
                ('obrigatorio', models.BooleanField(default=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('peso_match_codigo', models.PositiveSmallIntegerField(default=40)),
                ('peso_match_descricao', models.PositiveSmallIntegerField(default=25)),
                ('peso_match_ncm', models.PositiveSmallIntegerField(default=15)),
                ('observacoes', models.TextField(blank=True)),
                ('equivalencia_composta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='produtos.fornecedorcomposicaoequivalencia')),
                ('produto_componente_interno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equivalencias_composicao_componente', to='produtos.produto')),
            ],
            options={
                'ordering': ['equivalencia_composta_id', 'ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoComposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_composicao', models.CharField(choices=[('EQUIVALENCIA_FORNECEDOR', 'Equivalência fornecedor'), ('KIT_COMERCIAL', 'Kit comercial'), ('MONTAGEM_SIMPLES', 'Montagem simples'), ('MONTAGEM_ROSCADA', 'Montagem roscada'), ('MONTAGEM_COM_SERVICO_INTERNO', 'Montagem com serviço interno'), ('MONTAGEM_TERCEIRIZADA', 'Montagem terceirizada'), ('BENEFICIAMENTO', 'Beneficiamento')], max_length=40)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('permite_comprar_pronto', models.BooleanField(default=True)),
                ('permite_montar', models.BooleanField(default=True)),
                ('exige_confirmacao_operacional', models.BooleanField(default=True)),
                ('exige_servico', models.BooleanField(default=False)),
                ('tipo_servico', models.CharField(blank=True, max_length=64)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produto_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composicoes', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Composição de produto',
                'verbose_name_plural': 'Composições de produto',
                'ordering': ['produto_final_id', '-ativo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoComposicaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_por_unidade_final', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=14)),
                ('unidade', models.CharField(blank=True, max_length=16)),
                ('obrigatorio', models.BooleanField(default=True)),
                ('permite_substituto', models.BooleanField(default=False)),
                ('perda_percentual', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('observacoes', models.TextField(blank=True)),
                ('componente_produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='composicoes_como_componente', to='produtos.produto')),
                ('composicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='produtos.produtocomposicao')),
            ],
            options={
                'ordering': ['composicao_id', 'ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FornecedorProdutoEquivalencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_raiz_fornecedor', models.CharField(blank=True, db_index=True, max_length=8)),
                ('cnpj_filial_fornecedor', models.CharField(blank=True, db_index=True, max_length=14)),
                ('escopo_cnpj', models.CharField(choices=[('filial', 'Somente filial'), ('raiz', 'CNPJ raiz'), ('fornecedor', 'Fornecedor cadastrado')], default='raiz', max_length=16)),
                ('codigo_fornecedor', models.CharField(blank=True, db_index=True, max_length=64)),
                ('descricao_fornecedor_normalizada', models.CharField(blank=True, db_index=True, max_length=512)),
                ('ncm_fornecedor', models.CharField(blank=True, max_length=8)),
                ('unidade_fornecedor', models.CharField(blank=True, max_length=16)),
                ('fator_conversao', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=14)),
                ('tolerancia_quantidade', models.DecimalField(decimal_places=4, default=Decimal('0.01'), max_digits=14)),
                ('tolerancia_valor', models.DecimalField(decimal_places=2, default=Decimal('0.05'), max_digits=14)),
                ('ativo', models.BooleanField(default=True)),
                ('confianca_padrao', models.PositiveSmallIntegerField(default=90)),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('sugestao_confirmada', 'Sugestão confirmada'), ('importacao_historica', 'Importação histórica')], default='manual', max_length=32)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equivalencias_produto', to='cadastros.fornecedor')),
                ('produto_interno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equivalencias_fornecedor', to='produtos.produto')),
            ],
            options={
                'ordering': ['fornecedor_id', 'codigo_fornecedor', 'id'],
                'indexes': [models.Index(fields=['fornecedor', 'codigo_fornecedor'], name='produtos_fo_fornece_5a2253_idx'), models.Index(fields=['cnpj_raiz_fornecedor', 'codigo_fornecedor'], name='produtos_fo_cnpj_ra_74a95a_idx')],
            },
        ),
    ]
