# Generated by Django 5.2 on 2026-06-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0023_generalizacao_equivalencia_401371'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiaproduto',
            name='tipo_dimensional',
            field=models.CharField(
                choices=[
                    ('SIMPLES', 'Simples (somente regra de código)'),
                    ('NPS', 'NPS — polegada nominal'),
                    ('NPS_SCHEDULE', 'NPS + Schedule (SCH)'),
                    ('REDUCAO_NPS', 'Redução NPS + Schedule'),
                    ('ROSCA', 'Rosca / conexão (orientação)'),
                    ('ROSCA_X_ROSCA', 'Rosca x Rosca (orientação)'),
                    ('NPS_X_ROSCA', 'NPS x Rosca'),
                    ('OD_POLEGADA', 'OD em polegada (não é NPS/SCH)'),
                    ('OD_POLEGADA_X_ESPESSURA', 'OD em polegada + espessura mm'),
                    ('OD_POLEGADA_X_ROSCA', 'OD em polegada x Rosca'),
                    ('OD_MM', 'OD em mm (tubo / dimensional)'),
                    ('DN_MM', 'DN / medida em mm (PVC, CPVC, PPR, etc.)'),
                    ('DN_MM_REDUCAO', 'DN mm × DN mm (redução)'),
                    ('BITOLA_POLEGADA', 'Bitola em polegada (condulete / elétrico; tabela oficial)'),
                    ('OD_MM_REDUCAO', 'OD mm maior × menor (PU / pneumático)'),
                    ('OD_MM_X_ROSCA', 'OD mm × rosca ou bitola (PU / push-in)'),
                    ('OD_MM_X_ESPESSURA', 'OD mm + espessura mm'),
                    ('OD_MM_X_ESPESSURA_X_COMPRIMENTO', 'OD mm + espessura + comprimento'),
                    ('CHAPA_MM', 'Chapa em mm (espessura x largura x comprimento)'),
                    ('CHAPA_FURO_MM', 'Chapa com furo em mm (furo x espessura x largura x comprimento)'),
                    ('BARRA_CHATA_MM', 'Barra chata em mm (largura x espessura [x comprimento])'),
                    ('METALON_MM', 'Metalon em mm (altura x largura x espessura)'),
                    ('CANTONEIRA_MM', 'Cantoneira em mm (aba x espessura [x comprimento])'),
                    ('CANTONEIRA_POLEGADA', 'Cantoneira em polegada (aba x espessura)'),
                    ('PERFIL_RETANGULAR_MM', 'Perfil retangular em mm (altura x largura x espessura)'),
                    ('DIMENSIONAL_LIVRE_CONTROLADO', 'Dimensional livre controlado'),
                    ('FLANGE', 'Flange (orientação)'),
                    ('ESPIGAO_X_FLANGE', 'Espigão x Flange (duas NPS + texto flange na base)'),
                    ('VALVULA', 'Válvula (orientação)'),
                    ('MANUAL', 'Dimensional manual / sem padrão automático'),
                    ('LEGADO', 'Legado / misto (orientação)'),
                ],
                default='SIMPLES',
                help_text='Significado dimensional dos campos (rótulos, obrigatoriedade, descrição). '
                'A montagem do código continua definida apenas por tipo_regra_codigo.',
                max_length=48,
            ),
        ),
        migrations.AlterField(
            model_name='familiaproduto',
            name='tipo_regra_codigo',
            field=models.CharField(
                choices=[
                    ('BASE_POLEGADA', 'Base + polegada principal'),
                    ('BASE_ROSCA_POLEGADA', 'Base + rosca/conexão + polegada principal'),
                    ('BASE_DUAS_POLEGADAS', 'Base + duas polegadas (IDs)'),
                    ('BASE_ROSCA_DUAS_POLEGADAS', 'Base + rosca + duas polegadas'),
                    ('BASE_SCHEDULE_POLEGADA', 'Base + schedule + polegada principal'),
                    ('BASE_SCHEDULE_DUAS_POLEGADAS', 'Base + schedule + duas polegadas'),
                    ('BASE_ROSCA_SCHEDULE_POLEGADA', 'Base + rosca + schedule + polegada principal'),
                    (
                        'BASE_ROSCA_SCHEDULE_DUAS_POLEGADAS',
                        'Base + rosca + schedule + duas polegadas',
                    ),
                    ('UNDERSCORE_POLEGADA', 'Base + underscore + ID polegada (3 dígitos)'),
                    ('BASE_OD_MM_ESPESSURA', 'Base + OD mm + espessura mm (ex.: 6119OD.1002)'),
                    (
                        'BASE_OD_POLEGADA_ESPESSURA',
                        'Base + OD polegada + espessura mm (ex.: 6119OD.040150)',
                    ),
                    ('BASE_DN_MM', 'Base + DN/mm (3 dígitos)'),
                    ('BASE_DN_MM_REDUCAO', 'Base + DN maior × menor (3+3 dígitos)'),
                    ('BASE_BITOLA_POLEGADA', 'Base + bitola (código da tabela de polegadas)'),
                    ('BASE_OD_MM', 'Base + OD mm (3 dígitos; PU / pneumático)'),
                    ('BASE_OD_MM_REDUCAO', 'Base + OD mm maior × menor (3+3 dígitos)'),
                    ('BASE_OD_MM_X_ROSCA', 'Base + OD mm + rosca e/ou bitola'),
                    ('BASE_ESPIGAO_FLANGE_NPS', 'Base + espigão NPS + flange NPS'),
                    ('MANUAL_FABRICANTE', 'Manual / fabricante (sem código automático por família)'),
                ],
                default='BASE_POLEGADA',
                max_length=48,
            ),
        ),
    ]
