# Generated by Django 5.2 on 2026-07-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0025_controla_composicao_fisica'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiaproduto',
            name='tipo_composicao_fisica',
            field=models.CharField(choices=[('BARRA_M', 'Barra (comprimento em metros)'), ('PECA_KG', 'Peça/chapa (peso em kg)')], default='BARRA_M', help_text='BARRA_M: estoque base em metros por barra. PECA_KG: estoque base em kg por peça/chapa.', max_length=16),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo_composicao_fisica',
            field=models.CharField(blank=True, choices=[('BARRA_M', 'Barra (comprimento em metros)'), ('PECA_KG', 'Peça/chapa (peso em kg)')], help_text='Vazio herda da família. BARRA_M: metros por barra. PECA_KG: kg por peça/chapa.', max_length=16),
        ),
        migrations.AlterField(
            model_name='familiaproduto',
            name='controla_composicao_fisica',
            field=models.BooleanField(default=False, help_text='Exige composição física na conferência (barra em metros ou peça/chapa em kg).'),
        ),
    ]
