# Generated by Django 5.2 on 2026-08-26 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0028_alter_familiaproduto_tipo_dimensional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoManometroSkuSequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_base', models.CharField(db_index=True, max_length=128, unique=True)),
                ('proximo_numero', models.PositiveIntegerField(default=1)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sequencias_sku_manometro', to='produtos.familiaproduto')),
                ('polegada_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sequencias_sku_manometro', to='produtos.polegada')),
                ('rosca_conexao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sequencias_sku_manometro', to='produtos.roscaconexao')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('proximo_numero__gte', 1)), name='ck_manometro_sku_seq_proximo_ge_1')],
            },
        ),
    ]
