# Generated by Django 5.2 on 2026-04-09 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=32)),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(blank=True, max_length=64)),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filhos', to='contabil.planoconta')),
            ],
            options={
                'verbose_name': 'Plano de contas',
                'verbose_name_plural': 'Plano de contas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('historico', models.CharField(blank=True, max_length=512)),
                ('tipo', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], max_length=1)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='contabil.planoconta')),
            ],
            options={
                'ordering': ['-data', 'id'],
            },
        ),
    ]
