# Generated by Django 5.2 on 2026-06-02 13:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0011_cliente_informacoes_complementares_nfe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Centros de custo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CondicaoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('quantidade_parcelas', models.PositiveSmallIntegerField(default=1)),
                ('intervalo_dias', models.PositiveSmallIntegerField(default=30)),
                ('primeiro_vencimento_dias', models.PositiveSmallIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ContaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('CAIXA', 'Caixa'), ('BANCO', 'Banco'), ('CARTEIRA', 'Carteira'), ('OUTRO', 'Outro')], default='CAIXA', max_length=16)),
                ('banco', models.CharField(blank=True, max_length=120)),
                ('agencia', models.CharField(blank=True, max_length=32)),
                ('conta', models.CharField(blank=True, max_length=32)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conta financeira',
                'verbose_name_plural': 'Contas financeiras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('tipo', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'Pix'), ('BOLETO', 'Boleto'), ('TRANSFERENCIA', 'Transferência'), ('CARTAO', 'Cartão'), ('CHEQUE', 'Cheque'), ('DEPOSITO', 'Depósito'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa'), ('AMBOS', 'Ambos')], default='AMBOS', max_length=12)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhas', to='financeiro.categoriafinanceira')),
            ],
            options={
                'verbose_name_plural': 'Categorias financeiras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TituloFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RECEBER', 'Conta a receber'), ('PAGAR', 'Conta a pagar')], db_index=True, max_length=12)),
                ('numero', models.CharField(db_index=True, max_length=40)),
                ('documento_origem', models.CharField(blank=True, max_length=80)),
                ('origem_tipo', models.CharField(choices=[('MANUAL', 'Manual'), ('PEDIDO_VENDA', 'Pedido de Venda'), ('FATURAMENTO', 'Faturamento'), ('NFE_SAIDA', 'NF-e Saída'), ('PEDIDO_COMPRA', 'Pedido de Compra'), ('NFE_ENTRADA', 'NF-e Entrada'), ('SERVICO', 'Serviço'), ('AJUSTE', 'Ajuste manual'), ('IMPORTACAO', 'Importação futura')], db_index=True, default='MANUAL', max_length=20)),
                ('origem_id', models.PositiveIntegerField(blank=True, null=True)),
                ('origem_descricao', models.CharField(blank=True, max_length=255)),
                ('origem_numero', models.CharField(blank=True, max_length=80)),
                ('origem_data', models.DateField(blank=True, null=True)),
                ('data_emissao', models.DateField()),
                ('data_vencimento', models.DateField(db_index=True)),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_aberto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_baixado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('status', models.CharField(choices=[('EM_ABERTO', 'Em aberto'), ('VENCIDO', 'Vencido'), ('PARCIALMENTE_RECEBIDO', 'Parcialmente recebido'), ('RECEBIDO', 'Recebido'), ('PARCIALMENTE_PAGO', 'Parcialmente pago'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], db_index=True, default='EM_ABERTO', max_length=32)),
                ('observacoes', models.TextField(blank=True)),
                ('cancelado', models.BooleanField(default=False)),
                ('motivo_cancelamento', models.TextField(blank=True)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulos', to='financeiro.categoriafinanceira')),
                ('centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulos', to='financeiro.centrocusto')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='titulos_financeiros', to='cadastros.cliente')),
                ('condicao_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulos', to='financeiro.condicaopagamento')),
                ('conta_financeira_prevista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulos_previstos', to='financeiro.contafinanceira')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulos_financeiros_criados', to=settings.AUTH_USER_MODEL)),
                ('forma_pagamento_prevista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulos_previstos', to='financeiro.formapagamento')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='titulos_financeiros', to='cadastros.fornecedor')),
            ],
            options={
                'ordering': ['-data_vencimento', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ParcelaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.PositiveSmallIntegerField()),
                ('data_vencimento', models.DateField()),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_aberto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_baixado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('status', models.CharField(default='EM_ABERTO', max_length=32)),
                ('observacoes', models.TextField(blank=True)),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='financeiro.titulofinanceiro')),
            ],
            options={
                'ordering': ['numero_parcela'],
            },
        ),
        migrations.CreateModel(
            name='FinanceiroEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIACAO', 'Criação'), ('EDICAO', 'Edição'), ('BAIXA', 'Baixa'), ('BAIXA_PARCIAL', 'Baixa parcial'), ('ESTORNO', 'Estorno de baixa'), ('CANCELAMENTO', 'Cancelamento'), ('VENCIMENTO', 'Alteração de vencimento'), ('VALOR', 'Alteração de valor')], max_length=20)),
                ('descricao', models.CharField(max_length=512)),
                ('dados_anteriores', models.JSONField(blank=True, default=dict)),
                ('dados_novos', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='financeiro.titulofinanceiro')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='BaixaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_baixa', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('juros', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('multa', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('tarifa', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('observacoes', models.TextField(blank=True)),
                ('estornada', models.BooleanField(default=False)),
                ('motivo_estorno', models.TextField(blank=True)),
                ('estornada_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('estornada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baixas_estornadas', to=settings.AUTH_USER_MODEL)),
                ('registrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baixas_registradas', to=settings.AUTH_USER_MODEL)),
                ('conta_financeira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baixas', to='financeiro.contafinanceira')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baixas', to='financeiro.formapagamento')),
                ('parcela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='baixas', to='financeiro.parcelafinanceira')),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baixas', to='financeiro.titulofinanceiro')),
            ],
            options={
                'ordering': ['-data_baixa', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='titulofinanceiro',
            index=models.Index(fields=['tipo', 'status'], name='financeiro__tipo_ed6367_idx'),
        ),
        migrations.AddIndex(
            model_name='titulofinanceiro',
            index=models.Index(fields=['tipo', 'data_vencimento'], name='financeiro__tipo_9d05cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parcelafinanceira',
            unique_together={('titulo', 'numero_parcela')},
        ),
    ]
