# Generated by Django 5.2 on 2026-06-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulofinanceiro',
            name='codigo_receita',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='titulofinanceiro',
            name='competencia',
            field=models.DateField(blank=True, help_text='Competência (ex.: primeiro dia do mês)', null=True),
        ),
        migrations.AddField(
            model_name='titulofinanceiro',
            name='descricao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='titulofinanceiro',
            name='numero_guia',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='titulofinanceiro',
            name='periodo_apuracao',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='titulofinanceiro',
            name='tipo_lancamento',
            field=models.CharField(blank=True, choices=[('FORNECEDOR', 'Fornecedor'), ('DESPESA_OPERACIONAL', 'Despesa operacional'), ('SERVICO', 'Serviço'), ('TRIBUTO_IMPOSTO', 'Tributo / Imposto'), ('OUTROS', 'Outros')], db_index=True, max_length=24),
        ),
        migrations.AddField(
            model_name='titulofinanceiro',
            name='tipo_tributo',
            field=models.CharField(blank=True, choices=[('ICMS', 'ICMS'), ('PIS', 'PIS'), ('COFINS', 'COFINS'), ('IPI', 'IPI'), ('ISS', 'ISS'), ('IBS', 'IBS'), ('CBS', 'CBS'), ('IR', 'IR'), ('CSLL', 'CSLL'), ('INSS', 'INSS'), ('FGTS', 'FGTS'), ('OUTROS', 'Outros')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='titulofinanceiro',
            name='origem_tipo',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('PEDIDO_VENDA', 'Pedido de Venda'), ('FATURAMENTO', 'Faturamento'), ('NFE_SAIDA', 'NF-e Saída'), ('PEDIDO_COMPRA', 'Pedido de Compra'), ('NFE_ENTRADA', 'NF-e Entrada'), ('SERVICO', 'Serviço'), ('AJUSTE', 'Ajuste manual'), ('IMPORTACAO', 'Importação futura'), ('APURACAO_FISCAL', 'Apuração fiscal (futuro)')], db_index=True, default='MANUAL', max_length=20),
        ),
    ]
