# Generated by Django 5.2 on 2026-06-02 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_despesa_tributo_pagar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titulofinanceiro',
            name='condicao_pagamento',
        ),
        migrations.DeleteModel(
            name='CondicaoPagamento',
        ),
    ]
