# Generated by Django 5.2 on 2026-06-02 16:05

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_cliente_informacoes_complementares_nfe'),
        ('financeiro', '0003_remover_condicao_pagamento_financeiro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titulofinanceiro',
            name='forma_pagamento_prevista',
        ),
        migrations.RemoveField(
            model_name='baixafinanceira',
            name='forma_pagamento',
        ),
        migrations.AddField(
            model_name='baixafinanceira',
            name='forma_pagamento_codigo',
            field=models.CharField(choices=[('PIX', 'Pix'), ('BOLETO', 'Boleto'), ('TRANSFERENCIA_BANCARIA', 'Transferência bancária'), ('DINHEIRO', 'Dinheiro'), ('CARTAO_CREDITO', 'Cartão de crédito'), ('CARTAO_DEBITO', 'Cartão de débito'), ('CHEQUE', 'Cheque'), ('DEPOSITO_BANCARIO', 'Depósito bancário'), ('SEM_MOVIMENTACAO_FINANCEIRA', 'Sem movimentação financeira'), ('OUTROS', 'Outros')], db_index=True, default='OUTROS', max_length=40),
        ),
        migrations.AddField(
            model_name='baixafinanceira',
            name='tipo_movimento',
            field=models.CharField(choices=[('RECEBIMENTO', 'Recebimento'), ('PAGAMENTO', 'Pagamento'), ('RECEBIMENTO_PARCIAL', 'Recebimento parcial'), ('PAGAMENTO_PARCIAL', 'Pagamento parcial'), ('ABATIMENTO', 'Abatimento'), ('ABATIMENTO_DEVOLUCAO', 'Abatimento por devolução'), ('GERACAO_CREDITO', 'Crédito gerado'), ('USO_CREDITO', 'Uso de crédito'), ('REEMBOLSO_CLIENTE', 'Reembolso ao cliente'), ('REEMBOLSO_FORNECEDOR', 'Reembolso do fornecedor'), ('ESTORNO', 'Estorno'), ('AJUSTE_MANUAL', 'Ajuste manual')], db_index=True, default='AJUSTE_MANUAL', max_length=24),
        ),
        migrations.AddField(
            model_name='titulofinanceiro',
            name='forma_pagamento_prevista_codigo',
            field=models.CharField(blank=True, choices=[('PIX', 'Pix'), ('BOLETO', 'Boleto'), ('TRANSFERENCIA_BANCARIA', 'Transferência bancária'), ('DINHEIRO', 'Dinheiro'), ('CARTAO_CREDITO', 'Cartão de crédito'), ('CARTAO_DEBITO', 'Cartão de débito'), ('CHEQUE', 'Cheque'), ('DEPOSITO_BANCARIO', 'Depósito bancário'), ('SEM_MOVIMENTACAO_FINANCEIRA', 'Sem movimentação financeira'), ('OUTROS', 'Outros')], max_length=32),
        ),
        migrations.AlterField(
            model_name='baixafinanceira',
            name='conta_financeira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='baixas', to='financeiro.contafinanceira'),
        ),
        migrations.AlterField(
            model_name='baixafinanceira',
            name='titulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='baixas', to='financeiro.titulofinanceiro'),
        ),
        migrations.AlterField(
            model_name='financeiroevento',
            name='acao',
            field=models.CharField(choices=[('CRIACAO', 'Criação'), ('EDICAO', 'Edição'), ('BAIXA', 'Baixa'), ('BAIXA_PARCIAL', 'Baixa parcial'), ('ESTORNO', 'Estorno de baixa'), ('CANCELAMENTO', 'Cancelamento'), ('VENCIMENTO', 'Alteração de vencimento'), ('VALOR', 'Alteração de valor'), ('ABATIMENTO_DEVOLUCAO', 'Abatimento por devolução'), ('USO_CREDITO', 'Uso de crédito')], max_length=24),
        ),
        migrations.CreateModel(
            name='CreditoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CLIENTE', 'Cliente'), ('FORNECEDOR', 'Fornecedor')], db_index=True, max_length=12)),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_utilizado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('PARCIALMENTE_UTILIZADO', 'Parcialmente utilizado'), ('UTILIZADO', 'Utilizado'), ('CANCELADO', 'Cancelado')], db_index=True, default='DISPONIVEL', max_length=24)),
                ('origem_tipo', models.CharField(choices=[('MANUAL', 'Manual'), ('DEVOLUCAO', 'Devolução'), ('AJUSTE', 'Ajuste'), ('NFE_DEVOLUCAO_FUTURO', 'NF-e de devolução (futuro)')], default='MANUAL', max_length=24)),
                ('origem_descricao', models.CharField(blank=True, max_length=255)),
                ('origem_numero', models.CharField(blank=True, max_length=80)),
                ('data_credito', models.DateField()),
                ('motivo', models.CharField(max_length=255)),
                ('observacoes', models.TextField(blank=True)),
                ('cancelado', models.BooleanField(default=False)),
                ('motivo_cancelamento', models.TextField(blank=True)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creditos_financeiros', to='cadastros.cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditos_criados', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creditos_financeiros', to='cadastros.fornecedor')),
            ],
            options={
                'ordering': ['-data_credito', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='baixafinanceira',
            name='credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='financeiro.creditofinanceiro'),
        ),
        migrations.CreateModel(
            name='CreditoFinanceiroEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIACAO', 'Criação'), ('APLICACAO', 'Crédito aplicado'), ('CANCELAMENTO', 'Cancelamento'), ('REEMBOLSO', 'Reembolso'), ('ESTORNO_APLICACAO', 'Estorno de aplicação')], max_length=24)),
                ('descricao', models.CharField(max_length=512)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('titulo_numero', models.CharField(blank=True, max_length=40)),
                ('baixa_id', models.PositiveIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='financeiro.creditofinanceiro')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.DeleteModel(
            name='FormaPagamento',
        ),
        migrations.AddIndex(
            model_name='creditofinanceiro',
            index=models.Index(fields=['tipo', 'status'], name='financeiro__tipo_11c0a7_idx'),
        ),
        migrations.AddIndex(
            model_name='creditofinanceiro',
            index=models.Index(fields=['cliente'], name='financeiro__cliente_c2f387_idx'),
        ),
        migrations.AddIndex(
            model_name='creditofinanceiro',
            index=models.Index(fields=['fornecedor'], name='financeiro__fornece_e3e0d8_idx'),
        ),
    ]
