# Generated by Django 5.2 on 2026-06-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_formas_fixas_creditos_movimentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditofinanceiro',
            name='origem_tipo',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('DEVOLUCAO', 'Devolução'), ('AJUSTE', 'Ajuste'), ('PAGAMENTO_A_MAIOR', 'Pagamento a maior'), ('OUTROS', 'Outros'), ('NFE_DEVOLUCAO_FUTURO', 'NF-e de devolução (futuro)')], default='MANUAL', max_length=24),
        ),
        migrations.AlterField(
            model_name='creditofinanceiroevento',
            name='acao',
            field=models.CharField(choices=[('CRIACAO', 'Criação'), ('EDICAO', 'Edição'), ('APLICACAO', 'Crédito aplicado'), ('CANCELAMENTO', 'Cancelamento'), ('REEMBOLSO', 'Reembolso'), ('ESTORNO_APLICACAO', 'Estorno de aplicação')], max_length=24),
        ),
    ]
