# Generated by Django 5.2 on 2026-08-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_alter_creditofinanceiro_origem_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulofinanceiro',
            name='origem_tipo',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('PEDIDO_VENDA', 'Pedido de Venda'), ('FATURAMENTO', 'Faturamento'), ('NFE_SAIDA', 'NF-e Saída'), ('PEDIDO_COMPRA', 'Pedido de Compra'), ('NFE_ENTRADA', 'NF-e Entrada'), ('CTE', 'CT-e'), ('SERVICO', 'Serviço'), ('AJUSTE', 'Ajuste manual'), ('IMPORTACAO', 'Importação futura'), ('APURACAO_FISCAL', 'Apuração fiscal (futuro)')], db_index=True, default='MANUAL', max_length=20),
        ),
    ]
