# Generated by Django 5.2 on 2026-04-09 17:57

import django.contrib.postgres.fields
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('comercial', '0001_initial'),
        ('corridas', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTeEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=64, unique=True)),
                ('valor_frete', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('data', models.DateField()),
                ('nfe_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('tomador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ctes_como_tomador', to='cadastros.empresa')),
                ('transportadora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ctes', to='cadastros.transportadora')),
            ],
            options={
                'verbose_name': 'CT-e entrada',
                'ordering': ['-data', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='NFeEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=64)),
                ('data', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nf_entradas_vinculadas', to='fiscal.cteentrada')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nf_entradas', to='cadastros.fornecedor')),
                ('pedido_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nf_entradas', to='comercial.pedidocompra')),
            ],
            options={
                'verbose_name': 'NF entrada',
                'ordering': ['-data', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='ItemNFeEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=14)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('corrida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='corridas.corrida')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
                ('nf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fiscal.nfeentrada')),
            ],
        ),
        migrations.CreateModel(
            name='NFeSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=64)),
                ('data', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('status', models.CharField(blank=True, max_length=64)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nf_saidas', to='cadastros.cliente')),
                ('pedido_venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nf_saidas', to='comercial.pedidovenda')),
            ],
            options={
                'verbose_name': 'NF saída',
                'ordering': ['-data', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='ItemNFeSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=14)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('corrida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='corridas.corrida')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
                ('nf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fiscal.nfesaida')),
            ],
        ),
        migrations.CreateModel(
            name='EstoqueCorrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('corrida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='corridas.corrida')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques_corrida', to='produtos.produto')),
            ],
            options={
                'ordering': ['produto_id', 'corrida_id'],
                'unique_together': {('produto', 'corrida')},
            },
        ),
    ]
