# Generated by Django 5.2 on 2026-04-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0010_nfe_entrada_conferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemnfeentrada',
            name='snapshot_produto',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='itemnfesaida',
            name='snapshot_produto',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
