# Generated by Django 5.2 on 2026-05-11 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0011_itemnfeentrada_snapshot_produto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoNFeSaidaHistoricaPendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_nfe', models.CharField(db_index=True, max_length=44)),
                ('tipo_evento', models.CharField(db_index=True, max_length=16)),
                ('descricao_evento', models.CharField(blank=True, max_length=255)),
                ('sequencia_evento', models.PositiveSmallIntegerField(default=0)),
                ('data_evento', models.DateTimeField(blank=True, null=True)),
                ('protocolo_evento', models.CharField(blank=True, max_length=30)),
                ('id_evento', models.CharField(blank=True, max_length=80)),
                ('justificativa', models.TextField(blank=True)),
                ('evento_json', models.JSONField(blank=True, default=dict)),
                ('nome_arquivo', models.CharField(blank=True, max_length=255)),
                ('direcao', models.CharField(choices=[('SAIDA', 'Saída'), ('ENTRADA', 'Entrada')], default='SAIDA', max_length=8)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APLICADO', 'Aplicado'), ('IGNORADO', 'Ignorado')], db_index=True, default='PENDENTE', max_length=12)),
                ('mensagem', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_pendentes_resolvidos', to='fiscal.nfesaidahistoricaimportada')),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
                'constraints': [models.UniqueConstraint(fields=('chave_nfe', 'tipo_evento', 'protocolo_evento', 'id_evento'), name='uniq_evento_hist_pendente_dedup')],
            },
        ),
    ]
