# Generated by Django 5.2 on 2026-05-17 00:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0012_evento_nfe_saida_historica_pendente'),
        ('produtos', '0021_alter_familia_tipo_dimensional_regra_pvc_pu'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfesaida',
            name='modo_atendimento_estoque',
            field=models.CharField(choices=[('IMEDIATO', 'Baixa física na emissão'), ('ANTECIPADO', 'Compromisso sem baixa física')], default='IMEDIATO', max_length=16),
        ),
        migrations.CreateModel(
            name='AtendimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_tipo', models.CharField(choices=[('NF_SAIDA', 'NF de saída')], default='NF_SAIDA', max_length=16)),
                ('quantidade_comprometida', models.DecimalField(decimal_places=3, max_digits=14)),
                ('quantidade_atendida', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('unidade', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PARCIAL', 'Parcial'), ('ATENDIDO', 'Atendido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=16)),
                ('estoque_fisico_aplicado', models.BooleanField(default=False)),
                ('estoque_aplicado_em', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atendido_em', models.DateTimeField(blank=True, null=True)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('item_nf_saida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos_estoque', to='fiscal.itemnfesaida')),
                ('nf_saida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos_estoque', to='fiscal.nfesaida')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos_estoque', to='produtos.produto')),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['produto', 'status'], name='fiscal_aten_produto_78f7fb_idx'), models.Index(fields=['nf_saida', 'status'], name='fiscal_aten_nf_said_afd063_idx'), models.Index(fields=['criado_em'], name='fiscal_aten_criado__4e3cab_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantidade_comprometida__gt', 0)), name='ck_atend_estoque_qtd_comprometida_pos'), models.CheckConstraint(condition=models.Q(('quantidade_atendida__gte', 0)), name='ck_atend_estoque_qtd_atendida_nonneg'), models.CheckConstraint(condition=models.Q(('status', 'CANCELADO'), ('quantidade_atendida__lte', models.F('quantidade_comprometida')), _connector='OR'), name='ck_atend_estoque_qtd_atend_lte_comp'), models.UniqueConstraint(condition=models.Q(models.Q(('status', 'CANCELADO'), _negated=True)), fields=('item_nf_saida',), name='uniq_atend_estoque_item_nf_saida_ativo')],
            },
        ),
    ]
