# Generated by Django 5.2 on 2026-05-17 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0013_atendimento_estoque_modo_nf_saida'),
        ('produtos', '0021_alter_familia_tipo_dimensional_regra_pvc_pu'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='atendimentoestoque',
            name='uniq_atend_estoque_item_nf_saida_ativo',
        ),
        migrations.AlterField(
            model_name='atendimentoestoque',
            name='item_nf_saida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_estoque', to='fiscal.itemnfesaida'),
        ),
        migrations.AddConstraint(
            model_name='atendimentoestoque',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('status', 'CANCELADO'), _negated=True), ('item_nf_saida__isnull', False)), fields=('item_nf_saida',), name='uniq_atend_estoque_item_nf_saida_ativo'),
        ),
    ]
