# Generated by Django 5.2 on 2026-05-17 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0014_atendimento_item_nf_saida_set_null'),
        ('qualidade', '0011_item_cf_rastreabilidade_conferencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtendimentoEstoqueLinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=14)),
                ('corrida_texto', models.CharField(blank=True, max_length=64)),
                ('lote', models.CharField(blank=True, max_length=64)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='fiscal.atendimentoestoque')),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linhas_atendimento_estoque', to='fiscal.nfeentradaconferencia')),
                ('item_certificado_fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linhas_atendimento_estoque', to='qualidade.itemcertificadofornecedorentrada')),
                ('item_conferencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linhas_atendimento_estoque', to='fiscal.itemnfeentradaconferencia')),
            ],
            options={
                'ordering': ['criado_em', 'id'],
                'indexes': [models.Index(fields=['atendimento'], name='fiscal_aten_atendim_fc84b5_idx'), models.Index(fields=['item_conferencia'], name='fiscal_aten_item_co_c99c9f_idx'), models.Index(fields=['conferencia'], name='fiscal_aten_confere_cce6f5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='ck_atend_estoque_linha_qtd_pos')],
            },
        ),
    ]
