# Generated by Django 5.2 on 2026-05-21 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0021_faturamentopedidovenda_nfe_saida_and_more'),
        ('fiscal', '0016_conferencia_estoque_aplicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemnfesaida',
            name='item_faturamento_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_nfe_saida', to='comercial.itemfaturamentopedidovenda'),
        ),
        migrations.AddField(
            model_name='itemnfesaida',
            name='snapshot_comercial',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemnfesaida',
            name='snapshot_fiscal',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfesaida',
            name='faturamento_pedido_venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nf_saidas_geradas', to='comercial.faturamentopedidovenda'),
        ),
        migrations.AddField(
            model_name='nfesaida',
            name='observacao_origem',
            field=models.TextField(blank=True, help_text='Observação da geração a partir do faturamento (rascunho).'),
        ),
    ]
