# Generated by Django 5.2 on 2026-05-21 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0018_nfe_saida_efeitos_eventos'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='nfesaidaevento',
            new_name='fiscal_nfes_nfe_sai_c34c32_idx',
            old_name='fiscal_nfes_nfe_sai_criado_idx',
        ),
    ]
