# Generated by Django 5.2 on 2026-05-22 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_colaborador'),
        ('fiscal', '0023_nfe_saida_status_conferencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NFeSefazStatusConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(default='SP', max_length=2)),
                ('ambiente', models.CharField(choices=[('homologacao', 'Homologação'), ('producao', 'Produção')], default='homologacao', max_length=16)),
                ('modelo', models.CharField(default='nfe', max_length=8)),
                ('sucesso', models.BooleanField(default=False)),
                ('c_stat', models.CharField(blank=True, max_length=8)),
                ('x_motivo', models.TextField(blank=True)),
                ('ver_aplic', models.CharField(blank=True, max_length=64)),
                ('tp_amb', models.CharField(blank=True, max_length=2)),
                ('c_uf', models.CharField(blank=True, max_length=4)),
                ('dh_recbto', models.CharField(blank=True, max_length=40)),
                ('t_med', models.CharField(blank=True, max_length=16)),
                ('versao_retorno', models.CharField(blank=True, max_length=8)),
                ('servico_operacional', models.BooleanField(default=False)),
                ('certificado_valido', models.BooleanField(default=False)),
                ('certificado_cnpj', models.CharField(blank=True, max_length=20)),
                ('certificado_validade_fim', models.DateField(blank=True, null=True)),
                ('xml_resposta', models.TextField(blank=True)),
                ('erro_tecnico', models.TextField(blank=True)),
                ('mensagens', models.JSONField(blank=True, default=list)),
                ('consultado_em', models.DateTimeField(auto_now_add=True)),
                ('consultado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_status_sefaz_nfe', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_status_sefaz', to='cadastros.empresa')),
            ],
            options={
                'verbose_name': 'Consulta status SEFAZ NF-e',
                'verbose_name_plural': 'Consultas status SEFAZ NF-e',
                'ordering': ['-consultado_em', '-id'],
            },
        ),
    ]
