# Generated by Django 5.2 on 2026-05-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0024_nfe_sefaz_status_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfesefazstatusconsulta',
            name='raw_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nfesefazstatusconsulta',
            name='tipo_erro',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='nfesefazstatusconsulta',
            name='traceback_resumido',
            field=models.TextField(blank=True),
        ),
    ]
