# Generated by Django 5.2 on 2026-05-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0026_nfe_saida_xml_preliminar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfesaida',
            name='chave_acesso_preliminar',
            field=models.CharField(blank=True, db_index=True, help_text='Chave calculada do XML preliminar — sem protocolo SEFAZ.', max_length=44),
        ),
        migrations.AlterField(
            model_name='nfesaida',
            name='numero_fiscal_preliminar',
            field=models.CharField(blank=True, help_text='nNF numérico no XML preliminar (não é o número interno RASCUNHO-*).', max_length=9),
        ),
        migrations.AlterField(
            model_name='nfesaida',
            name='serie_fiscal_preliminar',
            field=models.CharField(blank=True, help_text='Série fiscal no XML preliminar (homologação).', max_length=3),
        ),
        migrations.AlterField(
            model_name='nfesaida',
            name='xml_preliminar_gerado_em',
            field=models.DateTimeField(blank=True, help_text='Última geração do XML preliminar.', null=True),
        ),
    ]
