# Generated by Django 5.2 on 2026-05-24 04:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_cliente_informacoes_complementares_nfe'),
        ('comercial', '0031_normalizar_fat_legado'),
        ('fiscal', '0033_sync_status_autorizada_homologacao'),
        ('produtos', '0021_alter_familia_tipo_dimensional_regra_pvc_pu'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlocacaoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_necessaria', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('quantidade_atendida', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('quantidade_pendente', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('tipo_atendimento', models.CharField(choices=[('ESTOQUE_PROPRIO', 'Estoque próprio'), ('ENTRADA_CONCILIADA', 'Entrada conciliada'), ('RETIRADA_FORNECEDOR', 'Retirada no fornecedor'), ('ENTREGA_DIRETA_FORNECEDOR_CLIENTE', 'Entrega direta fornecedor → cliente'), ('RETIRADA_FORNECEDOR_TRANSPORTADORA', 'Retirada fornecedor → transportadora'), ('COMPRA_VINCULADA', 'Compra vinculada'), ('MISTO', 'Misto'), ('NAO_DEFINIDO', 'Não definido')], default='NAO_DEFINIDO', max_length=40)),
                ('status_entrada_fiscal', models.CharField(choices=[('NAO_APLICAVEL', 'Não aplicável'), ('PENDENTE', 'Pendente'), ('RECEBIDA', 'Recebida'), ('CONCILIADA', 'Conciliada'), ('DIVERGENTE', 'Divergente'), ('CANCELADA', 'Cancelada')], default='NAO_APLICAVEL', max_length=20)),
                ('origem_fisica', models.CharField(choices=[('ESTOQUE_PROPRIO', 'Estoque próprio'), ('FORNECEDOR', 'Fornecedor'), ('TRANSPORTADORA', 'Transportadora'), ('CLIENTE', 'Cliente'), ('TERCEIRO', 'Terceiro'), ('NAO_DEFINIDA', 'Não definida')], default='NAO_DEFINIDA', max_length=20)),
                ('destino_fisico', models.CharField(choices=[('CLIENTE', 'Cliente'), ('TRANSPORTADORA', 'Transportadora'), ('ESTOQUE_PROPRIO', 'Estoque próprio'), ('TERCEIRO', 'Terceiro'), ('NAO_DEFINIDO', 'Não definido')], default='NAO_DEFINIDO', max_length=20)),
                ('observacao_operacional', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('faturamento_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocacoes_atendimento', to='comercial.itemfaturamentopedidovenda')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocacoes_atendimento', to='cadastros.fornecedor')),
                ('item_nf_saida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocacoes_atendimento', to='fiscal.itemnfesaida')),
                ('nf_entrada_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocacoes_atendimento', to='fiscal.itemnfeentrada')),
                ('pedido_compra_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocacoes_atendimento', to='comercial.itempedidocompra')),
                ('pedido_venda_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocacoes_atendimento', to='comercial.itempedidovenda')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes_atendimento', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Alocação de atendimento',
                'verbose_name_plural': 'Alocações de atendimento',
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['produto', 'tipo_atendimento'], name='fiscal_aloc_produto_c3dfb7_idx'), models.Index(fields=['status_entrada_fiscal'], name='fiscal_aloc_status__d0c07e_idx'), models.Index(fields=['pedido_venda_item'], name='fiscal_aloc_pedido__bbb13e_idx')],
            },
        ),
    ]
