# Generated by Django 5.2 on 2026-05-30 02:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0031_normalizar_fat_legado'),
        ('fiscal', '0038_nfe_indicadores_fiscais_4013613'),
        ('produtos', '0021_alter_familia_tipo_dimensional_regra_pvc_pu'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFeEntradaAgrupamentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_usada', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('valor_usado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['agrupamento_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NFeEntradaAgrupamentoConferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_agrupamento', models.CharField(choices=[('equivalencia_simples', 'Equivalência simples'), ('equivalencia_composta', 'Equivalência composta'), ('montagem_planejada', 'Montagem planejada'), ('divergente', 'Divergente')], max_length=32)),
                ('status', models.CharField(choices=[('sugerido', 'Sugerido'), ('confirmado', 'Confirmado'), ('rejeitado', 'Rejeitado'), ('divergente', 'Divergente')], default='sugerido', max_length=16)),
                ('confianca', models.PositiveSmallIntegerField(default=0)),
                ('quantidade_equivalente', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('valor_total_agrupado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('valor_pedido_referencia', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('diferenca_valor', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('diferenca_quantidade', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('motivo_confirmacao', models.TextField(blank=True)),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True)),
                ('salvar_regra_fornecedor', models.BooleanField(default=False)),
                ('snapshot_rastreabilidade', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agrupamentos', to='fiscal.nfeentradaconferencia')),
                ('item_pedido_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agrupamentos_nfe_entrada', to='comercial.itempedidocompra')),
                ('pedido_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agrupamentos_nfe_entrada', to='comercial.pedidocompra')),
                ('produto_interno_resultante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agrupamentos_nfe_entrada', to='produtos.produto')),
            ],
            options={
                'ordering': ['conferencia_id', '-confianca', 'id'],
            },
        ),
    ]
