# Generated by Django 5.2 on 2026-05-30 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0039_equivalencia_composicao_40137'),
        ('produtos', '0022_equivalencia_composicao_40137'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nfeentradaagrupamentoconferencia',
            name='regra_equivalencia_composta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agrupamentos_conferencia', to='produtos.fornecedorcomposicaoequivalencia'),
        ),
        migrations.AddField(
            model_name='nfeentradaagrupamentoconferencia',
            name='regra_equivalencia_simples',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agrupamentos_conferencia', to='produtos.fornecedorprodutoequivalencia'),
        ),
        migrations.AddField(
            model_name='nfeentradaagrupamentoconferencia',
            name='usuario_confirmacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agrupamentos_nfe_entrada_confirmados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nfeentradaagrupamentoitem',
            name='agrupamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fiscal.nfeentradaagrupamentoconferencia'),
        ),
        migrations.AddField(
            model_name='nfeentradaagrupamentoitem',
            name='item_nfe_conferencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agrupamentos', to='fiscal.itemnfeentradaconferencia'),
        ),
        migrations.AddConstraint(
            model_name='nfeentradaagrupamentoitem',
            constraint=models.UniqueConstraint(fields=('item_nfe_conferencia',), name='uq_nfe_entrada_agrup_item_conf_unico'),
        ),
    ]
