# Generated by Django 5.2 on 2026-06-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0045_nfesaidaevento_carta_correcao_emitida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfesaida',
            name='status_emissao_sefaz',
            field=models.CharField(blank=True, choices=[('NUMERACAO_RESERVADA', 'Numeração reservada'), ('XML_GERADO', 'XML oficial gerado'), ('XML_ASSINADO', 'XML assinado'), ('ENVIADA_HOMOLOGACAO', 'Enviada homologação'), ('AUTORIZADA_HOMOLOGACAO', 'Autorizada homologação'), ('REJEITADA_HOMOLOGACAO', 'Rejeitada homologação'), ('ENVIADA_PRODUCAO', 'Enviada produção'), ('AUTORIZADA_PRODUCAO', 'Autorizada produção'), ('REJEITADA_PRODUCAO', 'Rejeitada produção'), ('ERRO_TRANSMISSAO', 'Erro transmissão'), ('LOTE_PROCESSADO_SEM_PROTOCOLO', 'Lote processado sem protocolo'), ('AGUARDANDO_PROCESSAMENTO', 'Aguardando processamento SEFAZ'), ('ERRO_RETORNO_SEFAZ', 'Erro retorno SEFAZ')], max_length=32),
        ),
    ]
