# Generated by Django 5.2 on 2026-06-17 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0047_nfesaidaevento_cancelamento_sefaz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NFeSaidaEnvioEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.CharField(max_length=320)),
                ('copias', models.TextField(blank=True, help_text='Destinatários em cópia (separados por vírgula).')),
                ('assunto', models.CharField(max_length=255)),
                ('ambiente', models.CharField(blank=True, max_length=16)),
                ('status_envio', models.CharField(choices=[('SUCESSO', 'Sucesso'), ('ERRO', 'Erro')], max_length=8)),
                ('mensagem_erro', models.TextField(blank=True)),
                ('anexo_xml', models.BooleanField(default=False)),
                ('anexo_danfe_pdf', models.BooleanField(default=False)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nf_saida_envios_email', to=settings.AUTH_USER_MODEL)),
                ('nfe_saida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_email', to='fiscal.nfesaida')),
            ],
            options={
                'verbose_name': 'Envio e-mail NF-e Saída',
                'verbose_name_plural': 'Envios e-mail NF-e Saída',
                'ordering': ['-enviado_em', '-id'],
                'indexes': [models.Index(fields=['nfe_saida', '-enviado_em'], name='fiscal_nfes_nfe_sai_b1695e_idx'), models.Index(fields=['status_envio', '-enviado_em'], name='fiscal_nfes_status__0c45d6_idx')],
            },
        ),
    ]
