# Generated by Django 5.2 on 2026-06-21 02:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_empresa_nfe_ambiente'),
        ('fiscal', '0048_nfesaidaenvioemail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NFeDestinadaManifestacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_acesso', models.CharField(db_index=True, max_length=44)),
                ('nsu', models.CharField(blank=True, db_index=True, max_length=20)),
                ('cnpj_destinatario', models.CharField(db_index=True, max_length=14)),
                ('cnpj_emitente', models.CharField(blank=True, db_index=True, max_length=14)),
                ('razao_social_emitente', models.CharField(blank=True, max_length=255)),
                ('ie_emitente', models.CharField(blank=True, max_length=20)),
                ('dh_emissao', models.DateTimeField(blank=True, null=True)),
                ('valor_nf', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('status_manifestacao', models.CharField(choices=[('PENDENTE', 'Pendente manifestação'), ('CIENTE', 'Ciência registrada'), ('CONFIRMADA', 'Confirmação da operação'), ('DESCONHECIDA', 'Desconhecimento'), ('NAO_REALIZADA', 'Operação não realizada'), ('ERRO', 'Erro SEFAZ')], db_index=True, default='PENDENTE', max_length=24)),
                ('status_xml', models.CharField(choices=[('RESUMO', 'Resumo recebido'), ('DISPONIVEL', 'XML disponível'), ('BAIXADO', 'XML baixado'), ('PENDENTE', 'Pendente XML'), ('ERRO', 'Erro')], db_index=True, default='RESUMO', max_length=16)),
                ('ambiente', models.CharField(choices=[('1', 'Produção'), ('2', 'Homologação')], db_index=True, default='1', max_length=1)),
                ('classificacao_dfe', models.CharField(blank=True, default='BASE_DFE_IMPORTADA', max_length=32)),
                ('ultimo_cstat', models.CharField(blank=True, max_length=8)),
                ('ultimo_xmotivo', models.CharField(blank=True, max_length=255)),
                ('resumo_json', models.JSONField(blank=True, default=dict)),
                ('manifestado_em', models.DateTimeField(blank=True, null=True)),
                ('xml_baixado_em', models.DateTimeField(blank=True, null=True)),
                ('consultado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfe_destinadas_manifestacao', to='cadastros.empresa')),
                ('nf_entrada_historica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfe_destinadas_manifestacao', to='fiscal.nfeentradahistoricaimportada')),
            ],
            options={
                'verbose_name': 'NF-e destinada (manifestação)',
                'verbose_name_plural': 'NF-e destinadas (manifestação)',
                'ordering': ['-dh_emissao', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NFeDestinadaManifestacaoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(choices=[('CONSULTA', 'Consulta DF-e'), ('MANIFESTACAO', 'Manifestação do destinatário'), ('BAIXA_XML', 'Download XML')], max_length=16)),
                ('codigo_evento', models.CharField(blank=True, max_length=16)),
                ('descricao', models.TextField()),
                ('ambiente', models.CharField(blank=True, max_length=1)),
                ('resultado_resumido', models.CharField(blank=True, max_length=255)),
                ('cstat', models.CharField(blank=True, max_length=8)),
                ('xmotivo', models.CharField(blank=True, max_length=255)),
                ('dados_json', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='fiscal.nfedestinadamanifestacao')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_manifestacao_destinatario', to='cadastros.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_manifestacao_destinatario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento manifestação destinatário',
                'verbose_name_plural': 'Eventos manifestação destinatário',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='nfedestinadamanifestacao',
            index=models.Index(fields=['empresa', 'status_manifestacao'], name='fiscal_nfed_empresa_e94aa7_idx'),
        ),
        migrations.AddIndex(
            model_name='nfedestinadamanifestacao',
            index=models.Index(fields=['empresa', 'status_xml'], name='fiscal_nfed_empresa_d181ff_idx'),
        ),
        migrations.AddIndex(
            model_name='nfedestinadamanifestacao',
            index=models.Index(fields=['empresa', '-dh_emissao'], name='fiscal_nfed_empresa_49b2ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='nfedestinadamanifestacao',
            constraint=models.UniqueConstraint(fields=('empresa', 'chave_acesso'), name='uq_nfe_destinada_manifestacao_empresa_chave'),
        ),
        migrations.AddIndex(
            model_name='nfedestinadamanifestacaoevento',
            index=models.Index(fields=['documento', '-criado_em'], name='fiscal_nfed_documen_713dd0_idx'),
        ),
    ]
