# Generated by Django 5.2 on 2026-06-23 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0055_nfesaidaevento_numeracao_recuperada_localmente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemnfesaida',
            options={'ordering': ['id']},
        ),
    ]
