# Generated by Django 5.2 on 2026-06-29 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0057_nfe_inutilizacao_sefaz'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='nfeinutilizacaosefaz',
            new_name='fiscal_nfei_configu_7378d3_idx',
            old_name='fiscal_nfe__configu_inut_idx',
        ),
    ]
