# Generated by Django 5.2 on 2026-07-07 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_cliente_enderecos_entrega_contatos'),
        ('fiscal', '0061_item_conferencia_conversao_estoque_auditoria'),
        ('produtos', '0025_controla_composicao_fisica'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueBarra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno_barra', models.CharField(db_index=True, max_length=64, unique=True)),
                ('comprimento_original_m', models.DecimalField(decimal_places=3, max_digits=14)),
                ('saldo_m', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unidade_base', models.CharField(default='M', max_length=8)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('PARCIAL', 'Parcial'), ('CONSUMIDA', 'Consumida'), ('CANCELADA', 'Cancelada')], default='DISPONIVEL', max_length=16)),
                ('origem', models.CharField(choices=[('CONFERENCIA_NFE_ENTRADA', 'Conferência NF-e entrada')], default='CONFERENCIA_NFE_ENTRADA', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('equivalencia_entrada', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='estoque_barra', to='fiscal.itemnfeentradaconferenciaequivalencia')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estoque_barras', to='cadastros.fornecedor')),
                ('item_conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque_barras', to='fiscal.itemnfeentradaconferencia')),
                ('nfe_entrada_historica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estoque_barras', to='fiscal.nfeentradahistoricaimportada')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque_barras', to='produtos.produto')),
            ],
            options={
                'ordering': ['item_conferencia_id', 'equivalencia_entrada__ordem', 'id'],
                'indexes': [models.Index(fields=['produto', 'status'], name='fiscal_esto_produto_1344b5_idx'), models.Index(fields=['item_conferencia'], name='fiscal_esto_item_co_afee72_idx')],
            },
        ),
    ]
