# Generated by Django 5.2 on 2026-07-07 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_cliente_enderecos_entrega_contatos'),
        ('fiscal', '0062_estoque_barra'),
        ('produtos', '0025_controla_composicao_fisica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoquebarra',
            options={'ordering': ['item_conferencia_id', 'equivalencia_entrada__ordem', 'sequencia_grupo', 'id']},
        ),
        migrations.AddField(
            model_name='estoquebarra',
            name='sequencia_grupo',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='itemnfeentradaconferenciaequivalencia',
            name='comprimento_unitario_m',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='itemnfeentradaconferenciaequivalencia',
            name='qtd_barras',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estoquebarra',
            name='equivalencia_entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoque_barras', to='fiscal.itemnfeentradaconferenciaequivalencia'),
        ),
        migrations.AddConstraint(
            model_name='estoquebarra',
            constraint=models.UniqueConstraint(fields=('equivalencia_entrada', 'sequencia_grupo'), name='uniq_estoque_barra_equiv_seq'),
        ),
    ]
