# Generated by Django 5.2 on 2026-07-31 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0066_nfe_entrada_conferencia_reabertura_evento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlocacaoAtendimentoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('CRIADA', 'Criada'), ('ATUALIZADA', 'Atualizada'), ('CONCILIADA', 'Conciliada (entrada × venda)'), ('QUANTIDADE_AJUSTADA', 'Quantidade ajustada'), ('DESVINCULADA', 'Desvinculada'), ('EXCLUIDA', 'Excluída')], db_index=True, max_length=32)),
                ('alocacao_id_snapshot', models.PositiveBigIntegerField(db_index=True)),
                ('ator_id_snapshot', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('ator_rotulo_snapshot', models.CharField(max_length=64)),
                ('nf_entrada_historica_item_id_snapshot', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('pedido_venda_item_id_snapshot', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('antes', models.JSONField(blank=True, default=dict)),
                ('depois', models.JSONField(blank=True, default=dict)),
                ('motivo', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('alocacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='fiscal.alocacaoatendimento')),
                ('ator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_alocacao_atendimento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de alocação de atendimento',
                'verbose_name_plural': 'Eventos de alocação de atendimento',
                'ordering': ['-criado_em', '-id'],
                'default_permissions': ('view',),
                'indexes': [models.Index(fields=['alocacao_id_snapshot', 'criado_em'], name='fisc_aloc_evt_aloc_cri_idx'), models.Index(fields=['nf_entrada_historica_item_id_snapshot', 'criado_em'], name='fisc_aloc_evt_hist_cri_idx'), models.Index(fields=['pedido_venda_item_id_snapshot', 'criado_em'], name='fisc_aloc_evt_pvi_cri_idx')],
            },
        ),
    ]
