# Generated by Django 5.2 on 2026-08-03 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0068_nfe_entrada_emissao_status_producao'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfeentrada',
            name='nfe_saida_origem',
            field=models.ForeignKey(blank=True, help_text='NF-e de saída que originou esta entrada própria (devolução/recusa).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_proprias_geradas', to='fiscal.nfesaida'),
        ),
    ]
