# Generated by Django 5.2 on 2026-08-03 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0069_nfe_entrada_saida_origem_devolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfeentrada',
            name='nfe_saida_historica_origem',
            field=models.ForeignKey(blank=True, help_text='NF-e saída importada por XML que originou esta entrada própria (devolução/recusa).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_proprias_geradas', to='fiscal.nfesaidahistoricaimportada'),
        ),
    ]
