# Generated by Django 5.2 on 2026-08-05 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0070_nfe_entrada_saida_historica_origem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ctehistoricoimportado',
            name='rateado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ctehistoricoimportado',
            name='rateado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctes_historicos_rateados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ctehistoricoimportado',
            name='rateio_frete_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
