# Generated by Django 5.2 on 2026-09-23 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0074_evento_impostos_atualizados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nfeentrada',
            name='efeitos_devolucao_aplicados_em',
            field=models.DateTimeField(blank=True, help_text='Quando o estorno de quantidade_faturada foi aplicado no pedido.', null=True),
        ),
        migrations.AddField(
            model_name='nfeentrada',
            name='efeitos_devolucao_por',
            field=models.ForeignKey(blank=True, help_text='Usuário que aplicou/estornou os efeitos da devolução.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='efeitos_devolucao_nfe_entrada_aplicados', to=settings.AUTH_USER_MODEL),
        ),
    ]
