# Generated by Django 5.2 on 2026-10-05 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0018_alter_colaborador_options_colaborador_bairro_and_more'),
        ('comercial', '0046_itempedidocompra_desconto_tipo'),
        ('fiscal', '0076_nfe_entrada_event_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nfesaida',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nf_saidas', to='cadastros.fornecedor'),
        ),
        migrations.AddField(
            model_name='nfesaida',
            name='nfe_entrada_conferencia_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nf_saidas_devolucao_compra', to='fiscal.nfeentradaconferencia'),
        ),
        migrations.AlterField(
            model_name='nfesaida',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nf_saidas', to='cadastros.cliente'),
        ),
        migrations.AddConstraint(
            model_name='nfesaida',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cliente__isnull', False), ('fornecedor__isnull', True)), models.Q(('cliente__isnull', True), ('fornecedor__isnull', False)), _connector='OR'), name='nf_saida_exatamente_um_de_cliente_fornecedor'),
        ),
    ]
