# Generated by Django 6.1.1 on 2026-10-06 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0077_nfe_saida_aceita_fornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDevolucaoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_devolvida', models.DecimalField(decimal_places=3, help_text='Quantidade (na unidade de estoque da conferência) devolvida.', max_digits=14)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('item_conferencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes_compra', to='fiscal.itemnfeentradaconferencia')),
                ('item_nf_saida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='devolucao_compra', to='fiscal.itemnfesaida')),
            ],
            options={
                'verbose_name': 'Item de devolução de compra',
                'verbose_name_plural': 'Itens de devolução de compra',
                'constraints': [models.UniqueConstraint(fields=('item_conferencia', 'item_nf_saida'), name='item_devolucao_compra_unico_por_item_saida')],
            },
        ),
    ]
