# Generated by Django 5.2 on 2026-10-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0078_item_devolucao_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfesaida',
            name='chave_nfe_referenciada',
            field=models.CharField(blank=True, help_text='Chave da NF-e referenciada (obrigatória quando fin_nfe=4).', max_length=44),
        ),
        migrations.AddField(
            model_name='nfesaida',
            name='fin_nfe',
            field=models.CharField(blank=True, default='1', help_text='finalidade da NF-e (1=normal, 4=devolução). Default: 1.', max_length=1),
        ),
    ]
