# Generated by Django 5.2 on 2026-04-09 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255)),
                ('cnpj', models.CharField(max_length=20)),
                ('ie', models.CharField(blank=True, max_length=32)),
                ('logradouro', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(blank=True, max_length=32)),
                ('complemento', models.CharField(blank=True, max_length=128)),
                ('bairro', models.CharField(blank=True, max_length=128)),
                ('cidade', models.CharField(blank=True, max_length=128)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=16)),
                ('telefone', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contato_responsavel', models.CharField(blank=True, max_length=255)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255)),
                ('cnpj', models.CharField(max_length=20)),
                ('ie', models.CharField(blank=True, max_length=32)),
                ('logradouro', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(blank=True, max_length=32)),
                ('complemento', models.CharField(blank=True, max_length=128)),
                ('bairro', models.CharField(blank=True, max_length=128)),
                ('cidade', models.CharField(blank=True, max_length=128)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=16)),
                ('telefone', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contato_responsavel', models.CharField(blank=True, max_length=255)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Transportadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=20)),
                ('ie', models.CharField(blank=True, max_length=32)),
                ('logradouro', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(blank=True, max_length=32)),
                ('complemento', models.CharField(blank=True, max_length=128)),
                ('bairro', models.CharField(blank=True, max_length=128)),
                ('cidade', models.CharField(blank=True, max_length=128)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=16)),
                ('telefone', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('placa_padrao', models.CharField(blank=True, max_length=16)),
                ('uf_placa', models.CharField(blank=True, max_length=2)),
            ],
            options={
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255)),
                ('cnpj', models.CharField(max_length=20)),
                ('ie', models.CharField(blank=True, max_length=32)),
                ('im', models.CharField(blank=True, max_length=32)),
                ('regime_tributario', models.CharField(blank=True, max_length=64)),
                ('logradouro', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(blank=True, max_length=32)),
                ('complemento', models.CharField(blank=True, max_length=128)),
                ('bairro', models.CharField(blank=True, max_length=128)),
                ('cidade', models.CharField(blank=True, max_length=128)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=16)),
                ('telefone', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site', models.CharField(blank=True, max_length=255)),
                ('certificado_digital', models.TextField(blank=True)),
                ('senha_certificado', models.CharField(blank=True, max_length=128)),
                ('empresa_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filiais', to='cadastros.empresa')),
            ],
            options={
                'ordering': ['razao_social'],
            },
        ),
    ]
