# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='certificado_digital',
        ),
        migrations.AddField(
            model_name='empresa',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='certificado_arquivo',
            field=models.FileField(blank=True, null=True, upload_to='empresas/certificados/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='certificado_validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='logotipo',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/logos/'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='transportadora',
            name='cnpj',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
