# Generated by Django 5.2 on 2026-04-14 19:25

import apps.cadastros.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_cadastro_ddd_banco_cnae_integracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicaopagamento',
            name='dias_parcelas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=apps.cadastros.models._default_dias_parcelas, size=None),
        ),
    ]
