# Generated by Django 5.2 on 2026-04-15 20:18

import apps.cadastros.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_remove_condicao_pagamento_and_text_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dias_parcelas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=apps.cadastros.models._default_dias_parcelas, size=None),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='dias_parcelas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=apps.cadastros.models._default_dias_parcelas, size=None),
        ),
    ]
