# Generated by Django 5.2 on 2026-07-24 19:40
#
# Somente AddField (ativo, recebe_documentos_fiscais). Sem UniqueConstraint.
# Preflight sugerido antes de endurecer unicidade no banco (fase posterior):
#   SELECT cliente_id, LOWER(TRIM(email)) AS email_norm, COUNT(*) AS qtd, ARRAY_AGG(id) AS ids
#   FROM cadastros_contatocliente
#   WHERE TRIM(email) <> ''
#   GROUP BY cliente_id, LOWER(TRIM(email))
#   HAVING COUNT(*) > 1;
# Não imprimir endereços reais em logs de diagnóstico — apenas qtd e ids.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_cliente_enderecos_entrega_contatos'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatocliente',
            name='ativo',
            field=models.BooleanField(
                default=True,
                help_text='Contato inativo permanece cadastrado, mas não é elegível para envio fiscal.',
            ),
        ),
        migrations.AddField(
            model_name='contatocliente',
            name='recebe_documentos_fiscais',
            field=models.BooleanField(
                default=False,
                help_text='Indica que o e-mail deste contato pode receber documentos fiscais (DANFE/XML).',
            ),
        ),
    ]
