# Generated by Django 5.2 on 2026-08-18 14:33

import apps.cadastros.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_contato_cliente_ativo_recebe_documentos_fiscais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportadora',
            name='cnpj',
            field=models.CharField(max_length=20, unique=True, validators=[apps.cadastros.utils.validar_cnpj_django]),
        ),
    ]
