# Generated by Django 5.2 on 2026-09-23 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0017_alter_transportadora_cnpj'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaborador',
            options={'ordering': ['nome'], 'permissions': [('ver_salario_colaborador', 'Pode ver salário e dados bancários')], 'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AddField(
            model_name='colaborador',
            name='bairro',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='celular',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cep',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cidade',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cnh_categoria',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cnh_numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cnh_validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cnpj',
            field=models.CharField(blank=True, db_index=True, max_length=18, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='complemento',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='ctps_emissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='ctps_numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='ctps_serie',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='ctps_uf',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='email_pessoal',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='emergencia_nome',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='emergencia_parentesco',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='emergencia_telefone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('', 'Não informado'), ('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUVO', 'Viúvo(a)'), ('UNIAO_ESTAVEL', 'União Estável')], max_length=20),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='identidade_emissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='identidade_numero',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='identidade_orgao',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='identidade_tipo',
            field=models.CharField(blank=True, choices=[('', 'Não informado'), ('RG', 'RG (legado)'), ('CIN', 'CIN'), ('OUTRO', 'Outro')], max_length=10),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='identidade_uf',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='identidade_validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='nacionalidade',
            field=models.CharField(blank=True, default='Brasileira', max_length=80),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='naturalidade_cidade',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='naturalidade_uf',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='nome_social',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='numero',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='pis_pasep',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='reservista_numero',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='sexo',
            field=models.CharField(blank=True, choices=[('', 'Não informado'), ('M', 'Masculino'), ('F', 'Feminino'), ('OUTRO', 'Outro'), ('NAO_INFORMAR', 'Prefiro não informar')], max_length=20),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='tipo_pessoa',
            field=models.CharField(choices=[('FISICA', 'Pessoa Física'), ('JURIDICA', 'Pessoa Jurídica')], default='FISICA', max_length=10),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='titulo_numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='titulo_secao',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='titulo_uf',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='titulo_zona',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='uf',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('parentesco', models.CharField(blank=True, max_length=60)),
                ('dependente_ir', models.BooleanField(default=False)),
                ('dependente_saude', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependentes', to='cadastros.colaborador')),
            ],
            options={
                'verbose_name': 'Dependente',
                'verbose_name_plural': 'Dependentes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contrato', models.CharField(blank=True, choices=[('', 'Não informado'), ('CLT', 'CLT'), ('PJ', 'PJ'), ('ESTAGIO', 'Estágio'), ('SOCIO', 'Sócio'), ('AUTONOMO', 'Autônomo'), ('TEMPORARIO', 'Temporário'), ('APRENDIZ', 'Aprendiz')], max_length=20)),
                ('matricula', models.CharField(blank=True, db_index=True, max_length=32)),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('data_demissao', models.DateField(blank=True, null=True)),
                ('motivo_demissao', models.CharField(blank=True, max_length=255)),
                ('cargo', models.CharField(blank=True, max_length=120)),
                ('departamento', models.CharField(blank=True, max_length=120)),
                ('cbo', models.CharField(blank=True, max_length=10)),
                ('local_trabalho', models.CharField(blank=True, max_length=120)),
                ('jornada_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('jornada_turno', models.CharField(blank=True, choices=[('', 'Não informado'), ('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite'), ('INTEGRAL', 'Integral'), ('COMERCIAL', 'Comercial')], max_length=20)),
                ('salario_base', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('salario_tipo', models.CharField(blank=True, choices=[('', 'Não informado'), ('MENSAL', 'Mensal'), ('HORISTA', 'Horista'), ('DIARIO', 'Diário'), ('COMISSAO', 'Por comissão')], max_length=20)),
                ('eh_vendedor', models.BooleanField(default=False)),
                ('eh_comprador', models.BooleanField(default=False)),
                ('eh_responsavel_fiscal', models.BooleanField(default=False)),
                ('eh_responsavel_financeiro', models.BooleanField(default=False)),
                ('eh_responsavel_estoque', models.BooleanField(default=False)),
                ('eh_responsavel_qualidade', models.BooleanField(default=False)),
                ('eh_administrador', models.BooleanField(default=False)),
                ('banco_codigo', models.CharField(blank=True, max_length=10)),
                ('banco_nome', models.CharField(blank=True, max_length=120)),
                ('agencia', models.CharField(blank=True, max_length=20)),
                ('conta', models.CharField(blank=True, max_length=30)),
                ('conta_digito', models.CharField(blank=True, max_length=5)),
                ('conta_tipo', models.CharField(blank=True, choices=[('', 'Não informado'), ('CORRENTE', 'Corrente'), ('POUPANCA', 'Poupança'), ('SALARIO', 'Salário')], max_length=20)),
                ('pix_tipo', models.CharField(blank=True, choices=[('', 'Não informado'), ('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('EMAIL', 'E-mail'), ('TELEFONE', 'Telefone'), ('ALEATORIA', 'Chave aleatória')], max_length=20)),
                ('pix_chave', models.CharField(blank=True, max_length=120)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('', 'Não informado'), ('DEPOSITO', 'Depósito'), ('PIX', 'PIX'), ('DINHEIRO', 'Dinheiro'), ('CHEQUE', 'Cheque')], max_length=20)),
                ('codigo_categoria_esocial', models.CharField(blank=True, max_length=10)),
                ('grau_instrucao', models.CharField(blank=True, max_length=50)),
                ('natureza_atividade', models.CharField(blank=True, max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='cadastros.colaborador')),
                ('empresa', models.ForeignKey(blank=True, help_text='Preparado para multi-company. Null = empresa única.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to='cadastros.empresa')),
                ('gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='cadastros.colaborador')),
            ],
            options={
                'verbose_name': 'Vínculo',
                'verbose_name_plural': 'Vínculos',
                'ordering': ['-data_admissao', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='EventoVinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ADMISSAO', 'Admissão'), ('PROMOCAO', 'Promoção'), ('AUMENTO', 'Aumento salarial'), ('TRANSFERENCIA', 'Transferência'), ('MUDANCA_JORNADA', 'Mudança de jornada'), ('MUDANCA_GESTOR', 'Mudança de gestor'), ('AFASTAMENTO', 'Afastamento'), ('RETORNO', 'Retorno de afastamento'), ('ENCERRAMENTO', 'Encerramento'), ('OUTRO', 'Outro')], max_length=20)),
                ('data_efetiva', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('observacao', models.TextField(blank=True)),
                ('dados_antes', models.JSONField(blank=True, null=True)),
                ('dados_depois', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_vinculo_registrados', to=settings.AUTH_USER_MODEL)),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='cadastros.vinculo')),
            ],
            options={
                'verbose_name': 'Evento de vínculo',
                'verbose_name_plural': 'Eventos de vínculo',
                'ordering': ['-data_efetiva', '-pk'],
            },
        ),
    ]
