# Generated by Django 5.2 on 2026-07-27 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_index=True, max_length=64)),
                ('model_name', models.CharField(db_index=True, max_length=64)),
                ('object_id', models.PositiveBigIntegerField(db_index=True)),
                ('operacao', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização')], max_length=16)),
                ('alteracoes', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoria',
                'verbose_name_plural': 'Registros de auditoria',
                'ordering': ['-criado_em', '-id'],
                'default_permissions': ('view',),
                'indexes': [models.Index(fields=['app_label', 'model_name', 'object_id'], name='auditoria_obj_lookup_idx')],
            },
        ),
    ]
