# Generated by Django 5.2 on 2026-04-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegraFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncm', models.CharField(max_length=16)),
                ('uf_origem', models.CharField(max_length=2)),
                ('uf_destino', models.CharField(max_length=2)),
                ('operacao', models.CharField(choices=[('Entrada', 'Entrada'), ('Saída', 'Saída')], max_length=16)),
                ('cfop', models.CharField(max_length=8)),
                ('cst_icms', models.CharField(blank=True, max_length=8)),
                ('aliquota_icms', models.FloatField(default=0)),
                ('cst_pis', models.CharField(blank=True, max_length=8)),
                ('aliquota_pis', models.FloatField(default=0)),
                ('cst_cofins', models.CharField(blank=True, max_length=8)),
                ('aliquota_cofins', models.FloatField(default=0)),
                ('cst_ipi', models.CharField(blank=True, max_length=8)),
                ('aliquota_ipi', models.FloatField(default=0)),
                ('base_calculo', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['ncm', 'uf_origem', 'uf_destino'],
                'indexes': [models.Index(fields=['ncm', 'uf_origem', 'uf_destino', 'operacao'], name='regras_fisc_ncm_a69527_idx')],
            },
        ),
    ]
