# Generated by Django 5.2 on 2026-05-16 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_alter_cliente_dias_parcelas_and_more'),
        ('produtos', '0021_alter_familia_tipo_dimensional_regra_pvc_pu'),
        ('regras_fiscais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraFiscalEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('codigo', models.CharField(blank=True, max_length=32)),
                ('ativo', models.BooleanField(default=True)),
                ('prioridade', models.IntegerField(default=0)),
                ('cfop', models.CharField(blank=True, max_length=8)),
                ('ncm', models.CharField(blank=True, max_length=16)),
                ('ncm_prefixo', models.BooleanField(default=False)),
                ('uf_origem', models.CharField(blank=True, max_length=2)),
                ('uf_destino', models.CharField(blank=True, max_length=2)),
                ('tipo_operacao_fiscal', models.CharField(blank=True, choices=[('COMPRA', 'Compra'), ('DEVOLUCAO_VENDA', 'Devolução de venda'), ('DEVOLUCAO_COMPRA', 'Devolução de compra'), ('REMESSA', 'Remessa'), ('BONIFICACAO', 'Bonificação'), ('USO_CONSUMO', 'Uso e consumo'), ('INDUSTRIALIZACAO', 'Industrialização'), ('OUTROS', 'Outros')], max_length=32)),
                ('cst_icms_esperado', models.CharField(blank=True, max_length=8)),
                ('csosn_esperado', models.CharField(blank=True, max_length=8)),
                ('cst_pis_esperado', models.CharField(blank=True, max_length=8)),
                ('cst_cofins_esperado', models.CharField(blank=True, max_length=8)),
                ('cst_ipi_esperado', models.CharField(blank=True, max_length=8)),
                ('movimenta_estoque', models.BooleanField(default=True)),
                ('exige_certificado_fornecedor', models.BooleanField(default=False)),
                ('permite_credito_fiscal', models.BooleanField(default=True)),
                ('severidade', models.CharField(choices=[('INFORMATIVO', 'Informativo'), ('ALERTA', 'Alerta'), ('BLOQUEIO', 'Bloqueio')], default='INFORMATIVO', max_length=16)),
                ('mensagem_padrao', models.CharField(blank=True, max_length=255)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regras_fiscais_entrada', to='cadastros.fornecedor')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regras_fiscais_entrada', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Regra fiscal de entrada',
                'verbose_name_plural': 'Regras fiscais de entrada',
                'ordering': ['-prioridade', 'nome', 'id'],
                'indexes': [models.Index(fields=['ativo', '-prioridade'], name='regras_fisc_ativo_56d0cb_idx'), models.Index(fields=['cfop'], name='regras_fisc_cfop_557faf_idx'), models.Index(fields=['ncm'], name='regras_fisc_ncm_83e5e6_idx')],
            },
        ),
    ]
