# Generated by Django 5.2 on 2026-05-17 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regras_fiscais', '0003_regra_fiscal_entrada_cfop_cenario'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='regrafiscalentrada',
            new_name='regras_fisc_cfop_or_f2b946_idx',
            old_name='regras_fisc_cfop_orig_idx',
        ),
    ]
