# Generated by Django 5.2 on 2026-05-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regras_fiscais', '0006_cenario_fiscal_entrada'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='regrafiscalentrada',
            new_name='regras_fisc_cenario_f61688_idx',
            old_name='regras_fisc_cenario_8a1f2d_idx',
        ),
        migrations.AlterField(
            model_name='regrafiscalentrada',
            name='descricao_cenario',
            field=models.CharField(blank=True, help_text='Rótulo da configuração (gerado automaticamente).', max_length=255),
        ),
    ]
