# Generated by Django 5.2 on 2026-05-18 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regras_fiscais', '0009_cenario_fiscal_saida'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='regrafiscalsaida',
            new_name='regras_fisc_ativo_e9258d_idx',
            old_name='regras_fisc_ativo_p_saida_idx',
        ),
        migrations.RenameIndex(
            model_name='regrafiscalsaida',
            new_name='regras_fisc_cfop_ve_50a342_idx',
            old_name='regras_fisc_cfop_v_saida_idx',
        ),
        migrations.RenameIndex(
            model_name='regrafiscalsaida',
            new_name='regras_fisc_cenario_14c288_idx',
            old_name='regras_fisc_cen_esc_saida_idx',
        ),
    ]
