# Generated by Django 5.2 on 2026-08-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regras_fiscais', '0013_regrafiscalsaida_difal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regrafiscalentrada',
            name='tipo_operacao_fiscal',
            field=models.CharField(blank=True, choices=[('COMPRA', 'Compra'), ('DEVOLUCAO_VENDA', 'Devolução de venda'), ('DEVOLUCAO_COMPRA', 'Devolução de compra'), ('REMESSA', 'Remessa'), ('BONIFICACAO', 'Bonificação'), ('USO_CONSUMO', 'Uso e consumo'), ('INDUSTRIALIZACAO', 'Industrialização'), ('FRETE_TRANSPORTE', 'Frete / transporte (CT-e)'), ('OUTROS', 'Outros')], max_length=32),
        ),
    ]
