# Generated by Django 5.2 on 2026-06-16 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0013_empresa_nfe_ambiente'),
        ('comercial', '0032_proposta_campos_comerciais'),
        ('fiscal', '0047_nfesaidaevento_cancelamento_sefaz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expedicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=32, unique=True)),
                ('tipo_operacao', models.CharField(choices=[('ESTOQUE_PROPRIO', 'Estoque próprio'), ('RETIRADA_FORNECEDOR', 'Retirada fornecedor'), ('ENTREGA_DIRETA_FORNECEDOR_CLIENTE', 'Entrega direta fornecedor → cliente'), ('RETIRADA_FORNECEDOR_TRANSPORTADORA', 'Retirada fornecedor → transportadora'), ('MISTO', 'Misto'), ('OUTROS', 'Outros')], max_length=48)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('AGUARDANDO_SEPARACAO', 'Aguardando separação'), ('AGUARDANDO_RETIRADA_FORNECEDOR', 'Aguardando retirada fornecedor'), ('MOTORISTA_ENVIADO', 'Motorista enviado'), ('RETIRADO_FORNECEDOR', 'Retirado fornecedor'), ('EM_TRANSITO', 'Em trânsito'), ('ENTREGUE_TRANSPORTADORA', 'Entregue transportadora'), ('ENTREGUE_CLIENTE', 'Entregue cliente'), ('OCORRENCIA', 'Ocorrência'), ('CANCELADO', 'Cancelado')], db_index=True, default='RASCUNHO', max_length=40)),
                ('motorista_nome', models.CharField(blank=True, max_length=120)),
                ('motorista_documento', models.CharField(blank=True, max_length=32)),
                ('telefone_motorista', models.CharField(blank=True, max_length=32)),
                ('placa_veiculo', models.CharField(blank=True, max_length=16)),
                ('volumes', models.PositiveIntegerField(default=0)),
                ('peso_bruto', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('peso_liquido', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('data_prevista_retirada', models.DateField(blank=True, null=True)),
                ('data_prevista_entrega', models.DateField(blank=True, null=True)),
                ('data_hora_retirada_real', models.DateTimeField(blank=True, null=True)),
                ('data_hora_entrega_real', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('ocorrencia_descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('alocacao_atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedicoes', to='fiscal.alocacaoatendimento')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedicoes_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedicoes', to='cadastros.cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedicoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('cte_entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedicoes', to='fiscal.cteentrada')),
                ('faturamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedicoes', to='comercial.faturamentopedidovenda')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedicoes', to='cadastros.fornecedor')),
                ('nfe_entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedicoes', to='fiscal.nfeentrada')),
                ('nfe_saida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedicoes', to='fiscal.nfesaida')),
                ('pedido_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedicoes', to='comercial.pedidocompra')),
                ('pedido_venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedicoes', to='comercial.pedidovenda')),
                ('transportadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedicoes', to='cadastros.transportadora')),
            ],
            options={
                'verbose_name': 'Expedição',
                'verbose_name_plural': 'Expedições',
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['status', '-criado_em'], name='expedicao_e_status_1bd0a6_idx'), models.Index(fields=['tipo_operacao', '-criado_em'], name='expedicao_e_tipo_op_478fee_idx'), models.Index(fields=['data_prevista_entrega'], name='expedicao_e_data_pr_22e1e3_idx'), models.Index(fields=['data_prevista_retirada'], name='expedicao_e_data_pr_8be348_idx')],
            },
        ),
    ]
