# Generated by Django 5.2 on 2026-08-06 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0016_contato_cliente_ativo_recebe_documentos_fiscais'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApuracaoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(db_index=True)),
                ('data_fim', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FECHADO', 'Fechado')], db_index=True, default='RASCUNHO', max_length=16)),
                ('tipo', models.CharField(default='AMBOS', max_length=16)),
                ('fonte', models.CharField(default='TODOS', max_length=16)),
                ('valor_entradas', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('valor_saidas', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('icms_debito', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('icms_credito', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('icms_st_debito', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('difal_valor', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('ipi_debito', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('ipi_credito', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('pis_debito', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('pis_credito', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cofins_debito', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cofins_credito', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('saldo_icms', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('totais_json', models.JSONField(blank=True, default=dict)),
                ('filtros_json', models.JSONField(blank=True, default=dict)),
                ('payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('versao_api_apuracao', models.CharField(blank=True, max_length=32)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apuracoes_fiscais_criadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apuracoes_fiscais', to='cadastros.empresa')),
                ('fechado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apuracoes_fiscais_fechadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Apuração fiscal',
                'verbose_name_plural': 'Apurações fiscais',
                'ordering': ['-data_inicio', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ApuracaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lado', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AMBOS', 'Ambos')], default='AMBOS', max_length=16)),
                ('origem_tipo', models.CharField(choices=[('AGRUPAMENTO_CFOP', 'Agrupamento CFOP'), ('AGRUPAMENTO_NCM', 'Agrupamento NCM'), ('NFE_ENTRADA_HIST', 'NF-e entrada histórica'), ('NFE_SAIDA_HIST', 'NF-e saída histórica'), ('NFE_ENTRADA', 'NF-e entrada operacional'), ('NFE_SAIDA', 'NF-e saída operacional'), ('CTE', 'CT-e'), ('OUTRO', 'Outro')], default='AGRUPAMENTO_CFOP', max_length=32)),
                ('origem_documento_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('origem_item_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('chave', models.CharField(blank=True, db_index=True, max_length=128)),
                ('cfop', models.CharField(blank=True, max_length=8)),
                ('ncm', models.CharField(blank=True, max_length=16)),
                ('cst_icms', models.CharField(blank=True, max_length=8)),
                ('cst_pis', models.CharField(blank=True, max_length=8)),
                ('cst_cofins', models.CharField(blank=True, max_length=8)),
                ('quantidade_itens', models.PositiveIntegerField(default=0)),
                ('valor_produtos', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('base_icms', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('valor_icms', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('base_icms_st', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('valor_icms_st', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('valor_fcp_st', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('valor_icms_uf_dest', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('base_ipi', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('valor_ipi', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('base_pis', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('valor_pis', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('base_cofins', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('valor_cofins', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('detalhe_json', models.JSONField(blank=True, default=dict)),
                ('apuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='apuracao_fiscal.apuracaofiscal')),
            ],
            options={
                'verbose_name': 'Item de apuração',
                'verbose_name_plural': 'Itens de apuração',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LogsAuditoriaApuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('ABRIU', 'Abriu rascunho'), ('FECHOU', 'Fechou período'), ('REABRIU', 'Reabriu período'), ('AJUSTE_ADICIONADO', 'Ajuste adicionado'), ('AJUSTE_REMOVIDO', 'Ajuste removido'), ('ATUALIZOU_RASCUNHO', 'Atualizou rascunho')], db_index=True, max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('detalhe', models.JSONField(blank=True, default=dict)),
                ('apuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_auditoria', to='apuracao_fiscal.apuracaofiscal')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria_apuracao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de auditoria da apuração',
                'verbose_name_plural': 'Logs de auditoria da apuração',
                'ordering': ['-timestamp', '-id'],
                'default_permissions': ('view',),
            },
        ),
        migrations.AddIndex(
            model_name='apuracaofiscal',
            index=models.Index(fields=['empresa', 'status', 'data_inicio'], name='apuracao_emp_st_ini_idx'),
        ),
        migrations.AddConstraint(
            model_name='apuracaofiscal',
            constraint=models.UniqueConstraint(fields=('empresa', 'data_inicio', 'data_fim'), name='apuracao_fiscal_empresa_periodo_uniq'),
        ),
        migrations.AddIndex(
            model_name='apuracaoitem',
            index=models.Index(fields=['apuracao', 'cfop'], name='apuracao_item_cfop_idx'),
        ),
    ]
