# Generated by Django 5.2 on 2026-08-06 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuracao_fiscal', '0001_apuracao_persistida_f1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApuracaoAjusteManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('ESTORNO', 'Estorno')], db_index=True, max_length=16)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=16)),
                ('motivo', models.CharField(max_length=500)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('apuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_manuais', to='apuracao_fiscal.apuracaofiscal')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_manuais_apuracao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ajuste manual de apuração',
                'verbose_name_plural': 'Ajustes manuais de apuração',
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['apuracao', 'tipo'], name='apuracao_ajuste_tipo_idx')],
            },
        ),
    ]
