# Generated by Django 5.2 on 2026-08-06 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuracao_fiscal', '0002_apuracao_ajuste_manual_f2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApuracaoReforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbs_credito', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cbs_debito', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('ibs_credito', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('ibs_debito', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('is_valor', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('detalhe_json', models.JSONField(blank=True, default=dict)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('apuracao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reforma', to='apuracao_fiscal.apuracaofiscal')),
            ],
            options={
                'verbose_name': 'Apuração reforma tributária',
                'verbose_name_plural': 'Apurações reforma tributária',
            },
        ),
    ]
