# Generated by Django 5.2 on 2026-04-09 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=64, unique=True)),
                ('data_recebimento', models.DateField()),
                ('nf_entrada', models.CharField(blank=True, max_length=64)),
                ('composicao_quimica', models.JSONField(default=dict)),
                ('tracao', models.JSONField(default=dict)),
                ('impacto', models.JSONField(default=dict)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corridas', to='cadastros.fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corridas', to='produtos.produto')),
            ],
            options={
                'ordering': ['-data_recebimento', 'numero'],
            },
        ),
    ]
