"""Códigos de tipo de erro — diagnóstico SEFAZ NF-e 3.6.1."""

TIPO_ERRO_CERTIFICADO = 'CERTIFICADO_ERROR'
TIPO_ERRO_EMPRESA_BLOQUEADA = 'EMPRESA_BLOQUEADA'
TIPO_ERRO_PYNFE = 'PYNFE_ERROR'
TIPO_ERRO_PARSE = 'PARSE_ERROR'
TIPO_ERRO_RESPOSTA_VAZIA = 'RESPOSTA_VAZIA'
TIPO_ERRO_CONEXAO = 'CONEXAO_ERROR'
TIPO_ERRO_SEFAZ = 'SEFAZ_ERROR'  # cStat recebido, serviço não em operação (≠ 107/108)
TIPO_ERRO_GENERICO = 'GENERICO'
