# Generated by Django 5.2 on 2026-04-09 17:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('corridas', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=32, unique=True)),
                ('data', models.DateField()),
                ('status', models.CharField(blank=True, max_length=64)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra', to='cadastros.fornecedor')),
            ],
            options={
                'ordering': ['-data', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=14)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='comercial.pedidocompra')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=32, unique=True)),
                ('data', models.DateField()),
                ('status', models.CharField(blank=True, max_length=64)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_venda', to='cadastros.cliente')),
            ],
            options={
                'ordering': ['-data', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=14)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('corrida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corridas.corrida')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='comercial.pedidovenda')),
            ],
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=32, unique=True)),
                ('data', models.DateField()),
                ('validade', models.DateField()),
                ('vendedor', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=64)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propostas', to='cadastros.cliente')),
            ],
            options={
                'ordering': ['-data', 'numero'],
            },
        ),
        migrations.AddField(
            model_name='pedidovenda',
            name='proposta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_gerados', to='comercial.proposta'),
        ),
        migrations.CreateModel(
            name='ItemProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=14)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='comercial.proposta')),
            ],
        ),
    ]
