# Generated by Django 5.2 on 2026-04-29 02:14

import apps.comercial.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0008_item_unidade_dimensional_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocompra',
            name='dias_parcelas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=apps.comercial.models._default_dias_parcelas, size=None),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='vencimentos_previstos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, default=apps.comercial.models._default_datas, size=None),
        ),
        migrations.AlterField(
            model_name='pedidovenda',
            name='dias_parcelas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=apps.comercial.models._default_dias_parcelas, size=None),
        ),
        migrations.AlterField(
            model_name='pedidovenda',
            name='vencimentos_previstos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, default=apps.comercial.models._default_datas, size=None),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='dias_parcelas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=apps.comercial.models._default_dias_parcelas, size=None),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='operacao_fiscal',
            field=models.CharField(default='Saída', help_text='Fluxo comercial: sempre saída; preenchido automaticamente.', max_length=16),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='uf_origem',
            field=models.CharField(blank=True, help_text='Denormalizado a partir da UF da empresa emitente (uso em regra fiscal).', max_length=2),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='vencimentos_previstos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, default=apps.comercial.models._default_datas, size=None),
        ),
    ]
