# Generated by Django 5.2 on 2026-04-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0009_alter_pedidocompra_dias_parcelas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedidocompra',
            name='snapshot_produto',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='itempedidovenda',
            name='snapshot_produto',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='itemproposta',
            name='snapshot_produto',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
