# Generated by Django 5.2 on 2026-05-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0011_pedido_compra_entrega_e_financeiro_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenciaPedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField(db_index=True, unique=True)),
                ('proximo_numero', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Sequência pedido de compra',
                'verbose_name_plural': 'Sequências pedidos de compra',
                'ordering': ['-data_referencia'],
            },
        ),
    ]
