# Generated by Django 5.2 on 2026-05-20 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0017_homologacao_fiscal_proposta_evento'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='homologacaofiscalpropostaevento',
            new_name='comercial_h_propost_41171e_idx',
            old_name='comercial_h_proposta_criado_idx',
        ),
    ]
