# Generated by Django 5.2 on 2026-05-20 21:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0019_pedido_venda_conversao_proposta'),
        ('produtos', '0021_alter_familia_tipo_dimensional_regra_pvc_pu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedidovenda',
            name='quantidade_faturada',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Quantidade já confirmada em faturamentos (não inclui rascunhos).', max_digits=14),
        ),
        migrations.AddField(
            model_name='itempedidovenda',
            name='status_item',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PARCIAL', 'Parcialmente faturado'), ('FATURADO', 'Faturado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=16),
        ),
        migrations.CreateModel(
            name='FaturamentoPedidoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PRONTO_PARA_NFE', 'Pronto para NF-e'), ('GERADO_NFE', 'NF-e gerada'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=24)),
                ('cliente_snapshot', models.JSONField(blank=True, default=dict)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturamentos_pedido_venda_criados', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturamentos', to='comercial.pedidovenda')),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemFaturamentoPedidoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=14)),
                ('valor_unitario', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('snapshot_fiscal', models.JSONField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('faturamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='comercial.faturamentopedidovenda')),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_faturamento', to='comercial.itempedidovenda')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
