# Generated by Django 5.2 on 2026-05-21 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0020_pedido_venda_faturamento'),
        ('fiscal', '0016_conferencia_estoque_aplicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturamentopedidovenda',
            name='nfe_saida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturamento_vinculado', to='fiscal.nfesaida'),
        ),
        migrations.AddField(
            model_name='faturamentopedidovenda',
            name='nfe_saida_gerada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
