# Generated by Django 5.2 on 2026-05-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0027_prazo_entrega_texto_proposta_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidovenda',
            name='prazo_entrega',
            field=models.DateField(blank=True, help_text='Data prevista de entrega (legado/opcional); preferir prazo_entrega_texto.', null=True),
        ),
        migrations.AlterField(
            model_name='pedidovenda',
            name='prazo_entrega_texto',
            field=models.CharField(blank=True, default='', help_text='Prazo previsto de entrega herdado da proposta ou informado no pedido.', max_length=255),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='prazo_entrega_texto',
            field=models.CharField(blank=True, default='', help_text='Prazo previsto de entrega (texto livre, ex.: 30 dias após aprovação).', max_length=255),
        ),
    ]
