# Generated by Django 5.2 on 2026-06-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0033_status_comercial_proposta_persistente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propostacomercialhistorico',
            name='tipo_evento',
            field=models.CharField(choices=[('PROPOSTA_RECUPERADA', 'Proposta recuperada'), ('PEDIDO_GERADO', 'Pedido de venda gerado'), ('ITEM_CONVERTIDO', 'Item convertido em pedido'), ('ITEM_CANCELADO', 'Item cancelado'), ('ITEM_MANTIDO_PENDENTE', 'Item mantido pendente'), ('PEDIDO_EXCLUIDO_STATUS_REVERTIDO', 'Pedido excluído — status revertido'), ('REPARO_STATUS_COMERCIAL_PEDIDO', 'Reparo de status comercial (pedido excluído)')], max_length=32),
        ),
    ]
