# Generated by Django 5.2 on 2026-06-23 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0035_itempedidocompra_quantidade_recebida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itempedidovenda',
            options={'ordering': ['id']},
        ),
    ]
