# Generated by Django 5.2 on 2026-07-27 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_contato_cliente_ativo_recebe_documentos_fiscais'),
        ('comercial', '0036_ordenacao_itens_inclusao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseFinanceiraProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em análise'), ('APROVADA', 'Aprovada'), ('APROVADA_COM_AJUSTE', 'Aprovada com ajuste'), ('DEVOLVIDA_PARA_AJUSTE', 'Devolvida para ajuste'), ('NAO_APROVADA', 'Não aprovada'), ('EXPIRADA', 'Expirada'), ('SUBSTITUIDA', 'Substituída')], db_index=True, default='PENDENTE', max_length=32)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('solicitada_em', models.DateTimeField(auto_now_add=True)),
                ('iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('decidida_em', models.DateTimeField(blank=True, null=True)),
                ('observacao_vendedor', models.TextField(blank=True)),
                ('justificativa_decisao', models.TextField(blank=True)),
                ('valor_solicitado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_maximo_aprovado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('valida_ate', models.DateField(blank=True, null=True)),
                ('snapshot_proposta', models.JSONField(blank=True, default=dict)),
                ('snapshot_indicadores', models.JSONField(blank=True, default=dict)),
                ('condicao_solicitada', models.JSONField(blank=True, default=dict)),
                ('condicao_aprovada', models.JSONField(blank=True, default=dict)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analises_financeiras_proposta', to='cadastros.cliente')),
                ('decidida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_financeiras_decididas', to=settings.AUTH_USER_MODEL)),
                ('iniciada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_financeiras_iniciadas', to=settings.AUTH_USER_MODEL)),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises_financeiras', to='comercial.proposta')),
                ('solicitada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_financeiras_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('substituida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitui', to='comercial.analisefinanceiraproposta')),
            ],
            options={
                'verbose_name': 'Análise financeira de proposta',
                'verbose_name_plural': 'Análises financeiras de propostas',
                'ordering': ['-solicitada_em', '-id'],
                'permissions': (('solicitar_analisefinanceiraproposta', 'Pode solicitar análise financeira de proposta'), ('decidir_analisefinanceiraproposta', 'Pode decidir análise financeira de proposta'), ('ver_detalhe_financeiro_analisefinanceiraproposta', 'Pode ver detalhe financeiro da análise')),
            },
        ),
        migrations.CreateModel(
            name='AnaliseFinanceiraPropostaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('INICIADA', 'Iniciada'), ('APROVADA', 'Aprovada'), ('APROVADA_COM_AJUSTE', 'Aprovada com ajuste'), ('DEVOLVIDA', 'Devolvida'), ('NAO_APROVADA', 'Não aprovada'), ('EXPIRADA', 'Expirada'), ('SUBSTITUIDA', 'Substituída')], max_length=32)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='comercial.analisefinanceiraproposta')),
                ('ator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_analise_financeira_proposta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de análise financeira',
                'verbose_name_plural': 'Eventos de análise financeira',
                'ordering': ['-criado_em', '-id'],
                'default_permissions': ('view',),
            },
        ),
        migrations.AddIndex(
            model_name='analisefinanceiraproposta',
            index=models.Index(fields=['status', 'solicitada_em'], name='analise_fin_status_sol_idx'),
        ),
        migrations.AddIndex(
            model_name='analisefinanceiraproposta',
            index=models.Index(fields=['cliente', 'status'], name='analise_fin_cli_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='analisefinanceiraproposta',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDENTE', 'EM_ANALISE'])), fields=('proposta',), name='uniq_analise_fin_ativa_por_proposta'),
        ),
    ]
