# Generated by Django 5.2 on 2026-07-27 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0037_analise_financeira_proposta_mvp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaExternaAnaliseFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CADASTRAL', 'Cadastral'), ('BURO', 'Birô')], db_index=True, max_length=16)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('produto', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('CONCLUIDA', 'Concluída'), ('ERRO', 'Erro'), ('INDISPONIVEL', 'Indisponível'), ('EXPIRADA', 'Expirada')], db_index=True, default='PENDENTE', max_length=16)),
                ('solicitada_em', models.DateTimeField(auto_now_add=True)),
                ('iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('expira_em', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cnpj_mascarado', models.CharField(blank=True, max_length=32)),
                ('resultado_normalizado', models.JSONField(blank=True, default=dict)),
                ('erro_sanitizado', models.CharField(blank=True, max_length=255)),
                ('hash_requisicao', models.CharField(blank=True, db_index=True, max_length=64)),
                ('protocolo_mascarado', models.CharField(blank=True, max_length=64)),
                ('custo_consulta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('analise_financeira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas_externas', to='comercial.analisefinanceiraproposta')),
                ('solicitada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_externas_analise_financeira', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta externa da análise financeira',
                'verbose_name_plural': 'Consultas externas da análise financeira',
                'ordering': ['-solicitada_em', '-id'],
                'permissions': (('solicitar_consulta_cadastral_analise', 'Pode solicitar consulta cadastral na análise'), ('ver_resultado_cadastral_analise', 'Pode ver resultado cadastral da análise'), ('solicitar_consulta_buro_analise', 'Pode solicitar consulta de birô na análise'), ('ver_resultado_buro_analise', 'Pode ver resultado de birô da análise')),
                'default_permissions': ('view',),
                'indexes': [models.Index(fields=['analise_financeira', 'tipo', 'solicitada_em'], name='consulta_ext_analise_tipo_idx'), models.Index(fields=['status'], name='consulta_ext_status_idx'), models.Index(fields=['expira_em'], name='consulta_ext_expira_idx'), models.Index(fields=['hash_requisicao'], name='consulta_ext_hash_idx')],
            },
        ),
    ]
