# Generated by Django 5.2 on 2026-07-28 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0038_consulta_externa_analise_financeira_fundacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultaexternaanalisefinanceira',
            options={'default_permissions': ('view',), 'ordering': ['-solicitada_em', '-id'], 'permissions': (('solicitar_consulta_cadastral_analise', 'Pode solicitar consulta cadastral na análise'), ('ver_resultado_cadastral_analise', 'Pode ver resultado cadastral da análise'), ('solicitar_consulta_buro_analise', 'Pode solicitar consulta de birô na análise'), ('ver_resultado_buro_analise', 'Pode ver resultado de birô da análise'), ('registrar_protesto_manual_analise', 'Pode registrar protesto manual na análise'), ('ver_protesto_manual_analise', 'Pode ver protesto manual da análise')), 'verbose_name': 'Consulta externa da análise financeira', 'verbose_name_plural': 'Consultas externas da análise financeira'},
        ),
        migrations.AddField(
            model_name='consultaexternaanalisefinanceira',
            name='registro_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correcoes', to='comercial.consultaexternaanalisefinanceira'),
        ),
        migrations.AlterField(
            model_name='analisefinanceirapropostaevento',
            name='tipo',
            field=models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('INICIADA', 'Iniciada'), ('APROVADA', 'Aprovada'), ('APROVADA_COM_AJUSTE', 'Aprovada com ajuste'), ('DEVOLVIDA', 'Devolvida'), ('NAO_APROVADA', 'Não aprovada'), ('EXPIRADA', 'Expirada'), ('SUBSTITUIDA', 'Substituída'), ('PROTESTO_MANUAL_REGISTRADO', 'Protesto manual registrado')], max_length=32),
        ),
        migrations.AlterField(
            model_name='consultaexternaanalisefinanceira',
            name='tipo',
            field=models.CharField(choices=[('CADASTRAL', 'Cadastral'), ('BURO', 'Birô'), ('PROTESTO_MANUAL', 'Protesto manual')], db_index=True, max_length=16),
        ),
    ]
