# Generated by Django 5.2 on 2026-09-29 01:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0044_desconto_cabecalho_pedidovenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocompra',
            name='desconto_cabecalho',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Desconto aplicado no total do pedido (R$ ou % conforme desconto_cabecalho_tipo).', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='desconto_cabecalho_tipo',
            field=models.CharField(choices=[('valor', 'R$'), ('percentual', '%')], default='valor', help_text='Tipo do desconto do cabeçalho: valor em R$ ou percentual (%).', max_length=12),
        ),
    ]
